/******************************************************************************
 * TR-808
 * Virtual Analog Roland TR-808 Drum Machine
 * Component-level modeling with circuit bending modifications
 * Built with Faust DSP
 ******************************************************************************/

#include "rack.hpp"
#include "FaustModule.hpp"
#include "ImagePanel.hpp"
#define FAUST_MODULE_NAME TR808
#include "tr808.hpp"  // Generated by Faust

using namespace rack;

extern Plugin* pluginInstance;

namespace WiggleRoom {

/**
 * TR808 - Virtual Analog Drum Machine
 *
 * 12 drum voices with individual triggers and outputs:
 * - Bass Drum (BD), Snare Drum (SD)
 * - Low/Mid/High Tom (LT, MT, HT)
 * - Cowbell (CB), Closed Hat (CH), Open Hat (OH)
 * - Cymbal (CY), Clap (CP), Maracas (MA), Rimshot (RS)
 *
 * Circuit bending modifications available on most voices.
 * 13 outputs: 12 individual + master mix
 */
struct TR808 : FaustModule<VCVRackDSP> {
    // Voice indices for organization
    enum Voice {
        BD = 0, SD, LT, MT, HT, CB, CH, OH, CY, CP, MA, RS,
        NUM_VOICES
    };

    enum ParamId {
        // Bass Drum
        BD_DECAY_PARAM,
        BD_TUNE_PARAM,
        BD_TONE_PARAM,
        BD_CLICK_PARAM,
        BD_LONG_DECAY_PARAM,
        BD_DRIVE_PARAM,

        // Snare Drum
        SD_TUNE_PARAM,
        SD_TONE_PARAM,
        SD_SNAPPY_PARAM,
        SD_SNAP_DECAY_PARAM,
        SD_SNAP_FILTER_PARAM,
        SD_DETUNE_PARAM,

        // Low Tom
        LT_TUNE_PARAM,
        LT_DECAY_PARAM,
        LT_PITCH_MOD_PARAM,

        // Mid Tom
        MT_TUNE_PARAM,
        MT_DECAY_PARAM,
        MT_PITCH_MOD_PARAM,

        // High Tom
        HT_TUNE_PARAM,
        HT_DECAY_PARAM,
        HT_PITCH_MOD_PARAM,

        // Cowbell
        CB_TUNE_PARAM,
        CB_DECAY_PARAM,
        CB_DETUNE_PARAM,

        // Closed Hat
        CH_TUNE_PARAM,
        CH_DECAY_PARAM,
        CH_SPREAD_PARAM,

        // Open Hat
        OH_TUNE_PARAM,
        OH_DECAY_PARAM,
        OH_SPREAD_PARAM,

        // Cymbal
        CY_TUNE_PARAM,
        CY_DECAY_PARAM,
        CY_TONE_PARAM,
        CY_SPREAD_PARAM,

        // Clap
        CP_REVERB_PARAM,
        CP_SPREAD_PARAM,
        CP_TONE_PARAM,

        // Maracas
        MA_DECAY_PARAM,
        MA_TONE_PARAM,

        // Rimshot
        RS_TUNE_PARAM,
        RS_DECAY_PARAM,

        // Master
        MASTER_COMP_PARAM,
        MASTER_GAIN_PARAM,
        MASTER_TONE_PARAM,

        PARAMS_LEN
    };

    enum InputId {
        // Trigger inputs (12)
        BD_TRIG_INPUT,
        SD_TRIG_INPUT,
        LT_TRIG_INPUT,
        MT_TRIG_INPUT,
        HT_TRIG_INPUT,
        CB_TRIG_INPUT,
        CH_TRIG_INPUT,
        OH_TRIG_INPUT,
        CY_TRIG_INPUT,
        CP_TRIG_INPUT,
        MA_TRIG_INPUT,
        RS_TRIG_INPUT,

        // CV inputs for tune parameters
        BD_TUNE_CV_INPUT,
        SD_TUNE_CV_INPUT,
        LT_TUNE_CV_INPUT,
        MT_TUNE_CV_INPUT,
        HT_TUNE_CV_INPUT,
        CB_TUNE_CV_INPUT,
        CH_TUNE_CV_INPUT,
        OH_TUNE_CV_INPUT,
        CY_TUNE_CV_INPUT,

        // CV inputs for main parameters
        BD_DECAY_CV_INPUT,
        SD_SNAPPY_CV_INPUT,
        CH_SPREAD_CV_INPUT,
        OH_SPREAD_CV_INPUT,

        INPUTS_LEN
    };

    enum OutputId {
        // Individual voice outputs (12)
        BD_OUTPUT,
        SD_OUTPUT,
        LT_OUTPUT,
        MT_OUTPUT,
        HT_OUTPUT,
        CB_OUTPUT,
        CH_OUTPUT,
        OH_OUTPUT,
        CY_OUTPUT,
        CP_OUTPUT,
        MA_OUTPUT,
        RS_OUTPUT,

        // Master mix
        MIX_OUTPUT,

        OUTPUTS_LEN
    };

    enum LightId {
        // Trigger LEDs (12)
        BD_LIGHT,
        SD_LIGHT,
        LT_LIGHT,
        MT_LIGHT,
        HT_LIGHT,
        CB_LIGHT,
        CH_LIGHT,
        OH_LIGHT,
        CY_LIGHT,
        CP_LIGHT,
        MA_LIGHT,
        RS_LIGHT,

        LIGHTS_LEN
    };

    // Light decay for trigger LEDs
    float lightValues[NUM_VOICES] = {};
    static constexpr float LIGHT_DECAY = 0.05f;

    TR808() {
        config(PARAMS_LEN, INPUTS_LEN, OUTPUTS_LEN, LIGHTS_LEN);

        // Bass Drum params
        configParam(BD_DECAY_PARAM, 0.0f, 1.0f, 0.5f, "BD Decay", "%", 0.f, 100.f);
        configParam(BD_TUNE_PARAM, -1.0f, 1.0f, 0.0f, "BD Tune", " semitones", 0.f, 6.f);
        configParam(BD_TONE_PARAM, 0.0f, 1.0f, 0.5f, "BD Tone", "%", 0.f, 100.f);
        configParam(BD_CLICK_PARAM, 0.0f, 1.0f, 0.3f, "BD Click", "%", 0.f, 100.f);
        configParam(BD_LONG_DECAY_PARAM, 0.0f, 1.0f, 0.0f, "BD Long Decay", "%", 0.f, 100.f);
        configParam(BD_DRIVE_PARAM, 0.0f, 1.0f, 0.0f, "BD Drive", "%", 0.f, 100.f);

        // Snare Drum params
        configParam(SD_TUNE_PARAM, -1.0f, 1.0f, 0.0f, "SD Tune", " semitones", 0.f, 6.f);
        configParam(SD_TONE_PARAM, 0.0f, 1.0f, 0.5f, "SD Tone", "%", 0.f, 100.f);
        configParam(SD_SNAPPY_PARAM, 0.0f, 1.0f, 0.5f, "SD Snappy", "%", 0.f, 100.f);
        configParam(SD_SNAP_DECAY_PARAM, 0.0f, 1.0f, 0.3f, "SD Snap Decay", "%", 0.f, 100.f);
        configParam(SD_SNAP_FILTER_PARAM, 0.0f, 1.0f, 0.5f, "SD Snap Filter", "%", 0.f, 100.f);
        configParam(SD_DETUNE_PARAM, 0.0f, 1.0f, 0.0f, "SD Detune", "%", 0.f, 100.f);

        // Tom params
        configParam(LT_TUNE_PARAM, -1.0f, 1.0f, 0.0f, "LT Tune", " semitones", 0.f, 6.f);
        configParam(LT_DECAY_PARAM, 0.0f, 1.0f, 0.5f, "LT Decay", "%", 0.f, 100.f);
        configParam(LT_PITCH_MOD_PARAM, 0.0f, 1.0f, 0.0f, "LT Pitch Mod", "%", 0.f, 100.f);

        configParam(MT_TUNE_PARAM, -1.0f, 1.0f, 0.0f, "MT Tune", " semitones", 0.f, 6.f);
        configParam(MT_DECAY_PARAM, 0.0f, 1.0f, 0.5f, "MT Decay", "%", 0.f, 100.f);
        configParam(MT_PITCH_MOD_PARAM, 0.0f, 1.0f, 0.0f, "MT Pitch Mod", "%", 0.f, 100.f);

        configParam(HT_TUNE_PARAM, -1.0f, 1.0f, 0.0f, "HT Tune", " semitones", 0.f, 6.f);
        configParam(HT_DECAY_PARAM, 0.0f, 1.0f, 0.5f, "HT Decay", "%", 0.f, 100.f);
        configParam(HT_PITCH_MOD_PARAM, 0.0f, 1.0f, 0.0f, "HT Pitch Mod", "%", 0.f, 100.f);

        // Cowbell params
        configParam(CB_TUNE_PARAM, -1.0f, 1.0f, 0.0f, "CB Tune", " semitones", 0.f, 6.f);
        configParam(CB_DECAY_PARAM, 0.0f, 1.0f, 0.5f, "CB Decay", "%", 0.f, 100.f);
        configParam(CB_DETUNE_PARAM, 0.0f, 1.0f, 0.0f, "CB Detune", "%", 0.f, 100.f);

        // Closed Hat params
        configParam(CH_TUNE_PARAM, -1.0f, 1.0f, 0.0f, "CH Tune", " semitones", 0.f, 6.f);
        configParam(CH_DECAY_PARAM, 0.0f, 1.0f, 0.3f, "CH Decay", "%", 0.f, 100.f);
        configParam(CH_SPREAD_PARAM, 0.0f, 1.0f, 0.0f, "CH Spread", "%", 0.f, 100.f);

        // Open Hat params
        configParam(OH_TUNE_PARAM, -1.0f, 1.0f, 0.0f, "OH Tune", " semitones", 0.f, 6.f);
        configParam(OH_DECAY_PARAM, 0.0f, 1.0f, 0.6f, "OH Decay", "%", 0.f, 100.f);
        configParam(OH_SPREAD_PARAM, 0.0f, 1.0f, 0.0f, "OH Spread", "%", 0.f, 100.f);

        // Cymbal params
        configParam(CY_TUNE_PARAM, -1.0f, 1.0f, 0.0f, "CY Tune", " semitones", 0.f, 6.f);
        configParam(CY_DECAY_PARAM, 0.0f, 1.0f, 0.7f, "CY Decay", "%", 0.f, 100.f);
        configParam(CY_TONE_PARAM, 0.0f, 1.0f, 0.5f, "CY Tone", "%", 0.f, 100.f);
        configParam(CY_SPREAD_PARAM, 0.0f, 1.0f, 0.3f, "CY Spread", "%", 0.f, 100.f);

        // Clap params
        configParam(CP_REVERB_PARAM, 0.0f, 1.0f, 0.5f, "CP Reverb", "%", 0.f, 100.f);
        configParam(CP_SPREAD_PARAM, 0.0f, 1.0f, 0.3f, "CP Spread", "%", 0.f, 100.f);
        configParam(CP_TONE_PARAM, 0.0f, 1.0f, 0.5f, "CP Tone", "%", 0.f, 100.f);

        // Maracas params
        configParam(MA_DECAY_PARAM, 0.0f, 1.0f, 0.2f, "MA Decay", "%", 0.f, 100.f);
        configParam(MA_TONE_PARAM, 0.0f, 1.0f, 0.7f, "MA Tone", "%", 0.f, 100.f);

        // Rimshot params
        configParam(RS_TUNE_PARAM, -1.0f, 1.0f, 0.0f, "RS Tune", " semitones", 0.f, 6.f);
        configParam(RS_DECAY_PARAM, 0.0f, 1.0f, 0.3f, "RS Decay", "%", 0.f, 100.f);

        // Master params
        configParam(MASTER_COMP_PARAM, 0.0f, 1.0f, 0.5f, "Master Compression", "%", 0.f, 100.f);
        configParam(MASTER_GAIN_PARAM, 0.0f, 1.0f, 0.8f, "Master Gain", "%", 0.f, 100.f);
        configParam(MASTER_TONE_PARAM, 0.0f, 1.0f, 0.7f, "Master Tone", "%", 0.f, 100.f);

        // Trigger inputs
        configInput(BD_TRIG_INPUT, "BD Trigger");
        configInput(SD_TRIG_INPUT, "SD Trigger");
        configInput(LT_TRIG_INPUT, "LT Trigger");
        configInput(MT_TRIG_INPUT, "MT Trigger");
        configInput(HT_TRIG_INPUT, "HT Trigger");
        configInput(CB_TRIG_INPUT, "CB Trigger");
        configInput(CH_TRIG_INPUT, "CH Trigger");
        configInput(OH_TRIG_INPUT, "OH Trigger");
        configInput(CY_TRIG_INPUT, "CY Trigger");
        configInput(CP_TRIG_INPUT, "CP Trigger");
        configInput(MA_TRIG_INPUT, "MA Trigger");
        configInput(RS_TRIG_INPUT, "RS Trigger");

        // Tune CV inputs
        configInput(BD_TUNE_CV_INPUT, "BD Tune CV");
        configInput(SD_TUNE_CV_INPUT, "SD Tune CV");
        configInput(LT_TUNE_CV_INPUT, "LT Tune CV");
        configInput(MT_TUNE_CV_INPUT, "MT Tune CV");
        configInput(HT_TUNE_CV_INPUT, "HT Tune CV");
        configInput(CB_TUNE_CV_INPUT, "CB Tune CV");
        configInput(CH_TUNE_CV_INPUT, "CH Tune CV");
        configInput(OH_TUNE_CV_INPUT, "OH Tune CV");
        configInput(CY_TUNE_CV_INPUT, "CY Tune CV");

        // Other CV inputs
        configInput(BD_DECAY_CV_INPUT, "BD Decay CV");
        configInput(SD_SNAPPY_CV_INPUT, "SD Snappy CV");
        configInput(CH_SPREAD_CV_INPUT, "CH Spread CV");
        configInput(OH_SPREAD_CV_INPUT, "OH Spread CV");

        // Individual outputs
        configOutput(BD_OUTPUT, "BD");
        configOutput(SD_OUTPUT, "SD");
        configOutput(LT_OUTPUT, "LT");
        configOutput(MT_OUTPUT, "MT");
        configOutput(HT_OUTPUT, "HT");
        configOutput(CB_OUTPUT, "CB");
        configOutput(CH_OUTPUT, "CH");
        configOutput(OH_OUTPUT, "OH");
        configOutput(CY_OUTPUT, "CY");
        configOutput(CP_OUTPUT, "CP");
        configOutput(MA_OUTPUT, "MA");
        configOutput(RS_OUTPUT, "RS");
        configOutput(MIX_OUTPUT, "Mix");

        // Faust param mapping (alphabetical order)
        // bd_click=0, bd_decay=1, bd_drive=2, bd_long_decay=3, bd_tone=4, bd_trig=5, bd_tune=6
        // cb_decay=7, cb_detune=8, cb_trig=9, cb_tune=10
        // ch_decay=11, ch_spread=12, ch_trig=13, ch_tune=14
        // cp_reverb=15, cp_spread=16, cp_tone=17, cp_trig=18
        // cy_decay=19, cy_spread=20, cy_tone=21, cy_trig=22, cy_tune=23
        // ht_decay=24, ht_pitch_mod=25, ht_trig=26, ht_tune=27
        // lt_decay=28, lt_pitch_mod=29, lt_trig=30, lt_tune=31
        // ma_decay=32, ma_tone=33, ma_trig=34
        // master_comp=35, master_gain=36, master_tone=37
        // mt_decay=38, mt_pitch_mod=39, mt_trig=40, mt_tune=41
        // oh_decay=42, oh_spread=43, oh_trig=44, oh_tune=45
        // rs_decay=46, rs_trig=47, rs_tune=48
        // sd_detune=49, sd_snap_decay=50, sd_snap_filter=51, sd_snappy=52, sd_tone=53, sd_trig=54, sd_tune=55

        // Map params (we'll set triggers directly in process())
        mapParam(BD_CLICK_PARAM, 0);
        mapParam(BD_DECAY_PARAM, 1);
        mapParam(BD_DRIVE_PARAM, 2);
        mapParam(BD_LONG_DECAY_PARAM, 3);
        mapParam(BD_TONE_PARAM, 4);
        mapParam(BD_TUNE_PARAM, 6);
        mapParam(CB_DECAY_PARAM, 7);
        mapParam(CB_DETUNE_PARAM, 8);
        mapParam(CB_TUNE_PARAM, 10);
        mapParam(CH_DECAY_PARAM, 11);
        mapParam(CH_SPREAD_PARAM, 12);
        mapParam(CH_TUNE_PARAM, 14);
        mapParam(CP_REVERB_PARAM, 15);
        mapParam(CP_SPREAD_PARAM, 16);
        mapParam(CP_TONE_PARAM, 17);
        mapParam(CY_DECAY_PARAM, 19);
        mapParam(CY_SPREAD_PARAM, 20);
        mapParam(CY_TONE_PARAM, 21);
        mapParam(CY_TUNE_PARAM, 23);
        mapParam(HT_DECAY_PARAM, 24);
        mapParam(HT_PITCH_MOD_PARAM, 25);
        mapParam(HT_TUNE_PARAM, 27);
        mapParam(LT_DECAY_PARAM, 28);
        mapParam(LT_PITCH_MOD_PARAM, 29);
        mapParam(LT_TUNE_PARAM, 31);
        mapParam(MA_DECAY_PARAM, 32);
        mapParam(MA_TONE_PARAM, 33);
        mapParam(MASTER_COMP_PARAM, 35);
        mapParam(MASTER_GAIN_PARAM, 36);
        mapParam(MASTER_TONE_PARAM, 37);
        mapParam(MT_DECAY_PARAM, 38);
        mapParam(MT_PITCH_MOD_PARAM, 39);
        mapParam(MT_TUNE_PARAM, 41);
        mapParam(OH_DECAY_PARAM, 42);
        mapParam(OH_SPREAD_PARAM, 43);
        mapParam(OH_TUNE_PARAM, 45);
        mapParam(RS_DECAY_PARAM, 46);
        mapParam(RS_TUNE_PARAM, 48);
        mapParam(SD_DETUNE_PARAM, 49);
        mapParam(SD_SNAP_DECAY_PARAM, 50);
        mapParam(SD_SNAP_FILTER_PARAM, 51);
        mapParam(SD_SNAPPY_PARAM, 52);
        mapParam(SD_TONE_PARAM, 53);
        mapParam(SD_TUNE_PARAM, 55);
    }

    void process(const ProcessArgs& args) override {
        // Initialize DSP on first run
        if (!initialized) {
            faustDsp.init(static_cast<int>(args.sampleRate));
            initialized = true;
        }

        // Update params via mapParam
        updateFaustParams();

        // Apply CV modulation to tune params
        float bd_tune = params[BD_TUNE_PARAM].getValue();
        if (inputs[BD_TUNE_CV_INPUT].isConnected()) {
            bd_tune += inputs[BD_TUNE_CV_INPUT].getVoltage() * 0.2f;
            bd_tune = clamp(bd_tune, -1.f, 1.f);
        }
        faustDsp.setParamValue(6, bd_tune);

        float sd_tune = params[SD_TUNE_PARAM].getValue();
        if (inputs[SD_TUNE_CV_INPUT].isConnected()) {
            sd_tune += inputs[SD_TUNE_CV_INPUT].getVoltage() * 0.2f;
            sd_tune = clamp(sd_tune, -1.f, 1.f);
        }
        faustDsp.setParamValue(55, sd_tune);  // shifted +1

        // Apply CV modulation to other params
        float bd_decay = params[BD_DECAY_PARAM].getValue();
        if (inputs[BD_DECAY_CV_INPUT].isConnected()) {
            bd_decay += inputs[BD_DECAY_CV_INPUT].getVoltage() * 0.1f;
            bd_decay = clamp(bd_decay, 0.f, 1.f);
        }
        faustDsp.setParamValue(1, bd_decay);

        float sd_snappy = params[SD_SNAPPY_PARAM].getValue();
        if (inputs[SD_SNAPPY_CV_INPUT].isConnected()) {
            sd_snappy += inputs[SD_SNAPPY_CV_INPUT].getVoltage() * 0.1f;
            sd_snappy = clamp(sd_snappy, 0.f, 1.f);
        }
        faustDsp.setParamValue(52, sd_snappy);  // shifted +1

        // CH and OH tune - explicit handling to ensure tune works
        float ch_tune = params[CH_TUNE_PARAM].getValue();
        if (inputs[CH_TUNE_CV_INPUT].isConnected()) {
            ch_tune += inputs[CH_TUNE_CV_INPUT].getVoltage() * 0.2f;
            ch_tune = clamp(ch_tune, -1.f, 1.f);
        }
        faustDsp.setParamValue(14, ch_tune);  // ch_tune

        float oh_tune = params[OH_TUNE_PARAM].getValue();
        if (inputs[OH_TUNE_CV_INPUT].isConnected()) {
            oh_tune += inputs[OH_TUNE_CV_INPUT].getVoltage() * 0.2f;
            oh_tune = clamp(oh_tune, -1.f, 1.f);
        }
        faustDsp.setParamValue(45, oh_tune);  // oh_tune

        // CH and OH spread CV modulation
        float ch_spread = params[CH_SPREAD_PARAM].getValue();
        if (inputs[CH_SPREAD_CV_INPUT].isConnected()) {
            ch_spread += inputs[CH_SPREAD_CV_INPUT].getVoltage() * 0.1f;
            ch_spread = clamp(ch_spread, 0.f, 1.f);
        }
        faustDsp.setParamValue(12, ch_spread);  // ch_spread

        float oh_spread = params[OH_SPREAD_PARAM].getValue();
        if (inputs[OH_SPREAD_CV_INPUT].isConnected()) {
            oh_spread += inputs[OH_SPREAD_CV_INPUT].getVoltage() * 0.1f;
            oh_spread = clamp(oh_spread, 0.f, 1.f);
        }
        faustDsp.setParamValue(43, oh_spread);  // oh_spread

        // Get trigger inputs and send to Faust
        float bdTrig = inputs[BD_TRIG_INPUT].getVoltage();
        float sdTrig = inputs[SD_TRIG_INPUT].getVoltage();
        float ltTrig = inputs[LT_TRIG_INPUT].getVoltage();
        float mtTrig = inputs[MT_TRIG_INPUT].getVoltage();
        float htTrig = inputs[HT_TRIG_INPUT].getVoltage();
        float cbTrig = inputs[CB_TRIG_INPUT].getVoltage();
        float chTrig = inputs[CH_TRIG_INPUT].getVoltage();
        float ohTrig = inputs[OH_TRIG_INPUT].getVoltage();
        float cyTrig = inputs[CY_TRIG_INPUT].getVoltage();
        float cpTrig = inputs[CP_TRIG_INPUT].getVoltage();
        float maTrig = inputs[MA_TRIG_INPUT].getVoltage();
        float rsTrig = inputs[RS_TRIG_INPUT].getVoltage();

        // Set trigger params (Faust indices - shifted +1 after master_comp added)
        faustDsp.setParamValue(5, bdTrig);   // bd_trig
        faustDsp.setParamValue(9, cbTrig);   // cb_trig
        faustDsp.setParamValue(13, chTrig);  // ch_trig
        faustDsp.setParamValue(18, cpTrig);  // cp_trig
        faustDsp.setParamValue(22, cyTrig);  // cy_trig
        faustDsp.setParamValue(26, htTrig);  // ht_trig
        faustDsp.setParamValue(30, ltTrig);  // lt_trig
        faustDsp.setParamValue(34, maTrig);  // ma_trig
        faustDsp.setParamValue(40, mtTrig);  // mt_trig (shifted +1)
        faustDsp.setParamValue(44, ohTrig);  // oh_trig (shifted +1)
        faustDsp.setParamValue(47, rsTrig);  // rs_trig (shifted +1)
        faustDsp.setParamValue(54, sdTrig);  // sd_trig (shifted +1)

        // Update trigger LEDs
        if (bdTrig > 0.9f) lightValues[BD] = 1.0f;
        if (sdTrig > 0.9f) lightValues[SD] = 1.0f;
        if (ltTrig > 0.9f) lightValues[LT] = 1.0f;
        if (mtTrig > 0.9f) lightValues[MT] = 1.0f;
        if (htTrig > 0.9f) lightValues[HT] = 1.0f;
        if (cbTrig > 0.9f) lightValues[CB] = 1.0f;
        if (chTrig > 0.9f) lightValues[CH] = 1.0f;
        if (ohTrig > 0.9f) lightValues[OH] = 1.0f;
        if (cyTrig > 0.9f) lightValues[CY] = 1.0f;
        if (cpTrig > 0.9f) lightValues[CP] = 1.0f;
        if (maTrig > 0.9f) lightValues[MA] = 1.0f;
        if (rsTrig > 0.9f) lightValues[RS] = 1.0f;

        // Decay LEDs
        for (int i = 0; i < NUM_VOICES; i++) {
            lightValues[i] *= (1.0f - LIGHT_DECAY);
            lights[BD_LIGHT + i].setBrightness(lightValues[i]);
        }

        // Process audio (no input, 13 outputs)
        float* nullInputs[1] = { nullptr };
        float outputBuffers[13];
        float* outputPtrs[13];
        for (int i = 0; i < 13; i++) {
            outputBuffers[i] = 0.0f;
            outputPtrs[i] = &outputBuffers[i];
        }

        faustDsp.compute(1, nullInputs, outputPtrs);

        // Output individual voices at 5V peak
        outputs[BD_OUTPUT].setVoltage(outputBuffers[0] * 5.0f);
        outputs[SD_OUTPUT].setVoltage(outputBuffers[1] * 5.0f);
        outputs[LT_OUTPUT].setVoltage(outputBuffers[2] * 5.0f);
        outputs[MT_OUTPUT].setVoltage(outputBuffers[3] * 5.0f);
        outputs[HT_OUTPUT].setVoltage(outputBuffers[4] * 5.0f);
        outputs[CB_OUTPUT].setVoltage(outputBuffers[5] * 5.0f);
        outputs[CH_OUTPUT].setVoltage(outputBuffers[6] * 5.0f);
        outputs[OH_OUTPUT].setVoltage(outputBuffers[7] * 5.0f);
        outputs[CY_OUTPUT].setVoltage(outputBuffers[8] * 5.0f);
        outputs[CP_OUTPUT].setVoltage(outputBuffers[9] * 5.0f);
        outputs[MA_OUTPUT].setVoltage(outputBuffers[10] * 5.0f);
        outputs[RS_OUTPUT].setVoltage(outputBuffers[11] * 5.0f);

        // Master mix output
        outputs[MIX_OUTPUT].setVoltage(outputBuffers[12] * 5.0f);
    }
};

struct TR808Widget : ModuleWidget {
    TR808Widget(TR808* module) {
        setModule(module);
        box.size = Vec(26 * RACK_GRID_WIDTH, RACK_GRID_HEIGHT);
        addChild(new WiggleRoom::ImagePanel(
            asset::plugin(pluginInstance, "res/TR808.png"), box.size));

        // Screws
        addChild(createWidget<ScrewSilver>(Vec(RACK_GRID_WIDTH, 0)));
        addChild(createWidget<ScrewSilver>(Vec(box.size.x - 2 * RACK_GRID_WIDTH, 0)));
        addChild(createWidget<ScrewSilver>(Vec(RACK_GRID_WIDTH, RACK_GRID_HEIGHT - RACK_GRID_WIDTH)));
        addChild(createWidget<ScrewSilver>(Vec(box.size.x - 2 * RACK_GRID_WIDTH, RACK_GRID_HEIGHT - RACK_GRID_WIDTH)));

        // Layout: 12 voice rows + master row
        // Each row: Trigger in | Tune knob | Param knobs | LED | Output
        float startY = 18.f;  // mm from top
        float rowHeight = 8.5f;  // mm per voice row

        // Column positions (mm)
        float colTrigIn = 8.f;
        float colTune = 20.f;
        float colParam1 = 32.f;
        float colParam2 = 44.f;
        float colParam3 = 56.f;
        float colLed = 68.f;
        float colTuneCV = 80.f;
        float colOut = 92.f;
        float colParamCV1 = 104.f;
        float colParamCV2 = 116.f;

        // Voice names for reference
        const char* voiceNames[] = {"BD", "SD", "LT", "MT", "HT", "CB", "CH", "OH", "CY", "CP", "MA", "RS"};

        // === BASS DRUM (row 0) ===
        float y = startY;
        addInput(createInputCentered<PJ301MPort>(mm2px(Vec(colTrigIn, y)), module, TR808::BD_TRIG_INPUT));
        addParam(createParamCentered<Trimpot>(mm2px(Vec(colTune, y)), module, TR808::BD_TUNE_PARAM));
        addParam(createParamCentered<Trimpot>(mm2px(Vec(colParam1, y)), module, TR808::BD_DECAY_PARAM));
        addParam(createParamCentered<Trimpot>(mm2px(Vec(colParam2, y)), module, TR808::BD_TONE_PARAM));
        addParam(createParamCentered<Trimpot>(mm2px(Vec(colParam3, y)), module, TR808::BD_CLICK_PARAM));
        addChild(createLightCentered<SmallLight<RedLight>>(mm2px(Vec(colLed, y)), module, TR808::BD_LIGHT));
        addInput(createInputCentered<PJ301MPort>(mm2px(Vec(colTuneCV, y)), module, TR808::BD_TUNE_CV_INPUT));
        addOutput(createOutputCentered<PJ301MPort>(mm2px(Vec(colOut, y)), module, TR808::BD_OUTPUT));
        addInput(createInputCentered<PJ301MPort>(mm2px(Vec(colParamCV1, y)), module, TR808::BD_DECAY_CV_INPUT));
        addParam(createParamCentered<Trimpot>(mm2px(Vec(colParamCV2, y)), module, TR808::BD_LONG_DECAY_PARAM));

        // === SNARE DRUM (row 1) ===
        y = startY + rowHeight;
        addInput(createInputCentered<PJ301MPort>(mm2px(Vec(colTrigIn, y)), module, TR808::SD_TRIG_INPUT));
        addParam(createParamCentered<Trimpot>(mm2px(Vec(colTune, y)), module, TR808::SD_TUNE_PARAM));
        addParam(createParamCentered<Trimpot>(mm2px(Vec(colParam1, y)), module, TR808::SD_SNAPPY_PARAM));
        addParam(createParamCentered<Trimpot>(mm2px(Vec(colParam2, y)), module, TR808::SD_TONE_PARAM));
        addParam(createParamCentered<Trimpot>(mm2px(Vec(colParam3, y)), module, TR808::SD_SNAP_DECAY_PARAM));
        addChild(createLightCentered<SmallLight<RedLight>>(mm2px(Vec(colLed, y)), module, TR808::SD_LIGHT));
        addInput(createInputCentered<PJ301MPort>(mm2px(Vec(colTuneCV, y)), module, TR808::SD_TUNE_CV_INPUT));
        addOutput(createOutputCentered<PJ301MPort>(mm2px(Vec(colOut, y)), module, TR808::SD_OUTPUT));
        addInput(createInputCentered<PJ301MPort>(mm2px(Vec(colParamCV1, y)), module, TR808::SD_SNAPPY_CV_INPUT));
        addParam(createParamCentered<Trimpot>(mm2px(Vec(colParamCV2, y)), module, TR808::SD_DETUNE_PARAM));

        // === LOW TOM (row 2) ===
        y = startY + rowHeight * 2;
        addInput(createInputCentered<PJ301MPort>(mm2px(Vec(colTrigIn, y)), module, TR808::LT_TRIG_INPUT));
        addParam(createParamCentered<Trimpot>(mm2px(Vec(colTune, y)), module, TR808::LT_TUNE_PARAM));
        addParam(createParamCentered<Trimpot>(mm2px(Vec(colParam1, y)), module, TR808::LT_DECAY_PARAM));
        addParam(createParamCentered<Trimpot>(mm2px(Vec(colParam2, y)), module, TR808::LT_PITCH_MOD_PARAM));
        addChild(createLightCentered<SmallLight<RedLight>>(mm2px(Vec(colLed, y)), module, TR808::LT_LIGHT));
        addInput(createInputCentered<PJ301MPort>(mm2px(Vec(colTuneCV, y)), module, TR808::LT_TUNE_CV_INPUT));
        addOutput(createOutputCentered<PJ301MPort>(mm2px(Vec(colOut, y)), module, TR808::LT_OUTPUT));

        // === MID TOM (row 3) ===
        y = startY + rowHeight * 3;
        addInput(createInputCentered<PJ301MPort>(mm2px(Vec(colTrigIn, y)), module, TR808::MT_TRIG_INPUT));
        addParam(createParamCentered<Trimpot>(mm2px(Vec(colTune, y)), module, TR808::MT_TUNE_PARAM));
        addParam(createParamCentered<Trimpot>(mm2px(Vec(colParam1, y)), module, TR808::MT_DECAY_PARAM));
        addParam(createParamCentered<Trimpot>(mm2px(Vec(colParam2, y)), module, TR808::MT_PITCH_MOD_PARAM));
        addChild(createLightCentered<SmallLight<RedLight>>(mm2px(Vec(colLed, y)), module, TR808::MT_LIGHT));
        addInput(createInputCentered<PJ301MPort>(mm2px(Vec(colTuneCV, y)), module, TR808::MT_TUNE_CV_INPUT));
        addOutput(createOutputCentered<PJ301MPort>(mm2px(Vec(colOut, y)), module, TR808::MT_OUTPUT));

        // === HIGH TOM (row 4) ===
        y = startY + rowHeight * 4;
        addInput(createInputCentered<PJ301MPort>(mm2px(Vec(colTrigIn, y)), module, TR808::HT_TRIG_INPUT));
        addParam(createParamCentered<Trimpot>(mm2px(Vec(colTune, y)), module, TR808::HT_TUNE_PARAM));
        addParam(createParamCentered<Trimpot>(mm2px(Vec(colParam1, y)), module, TR808::HT_DECAY_PARAM));
        addParam(createParamCentered<Trimpot>(mm2px(Vec(colParam2, y)), module, TR808::HT_PITCH_MOD_PARAM));
        addChild(createLightCentered<SmallLight<RedLight>>(mm2px(Vec(colLed, y)), module, TR808::HT_LIGHT));
        addInput(createInputCentered<PJ301MPort>(mm2px(Vec(colTuneCV, y)), module, TR808::HT_TUNE_CV_INPUT));
        addOutput(createOutputCentered<PJ301MPort>(mm2px(Vec(colOut, y)), module, TR808::HT_OUTPUT));

        // === COWBELL (row 5) ===
        y = startY + rowHeight * 5;
        addInput(createInputCentered<PJ301MPort>(mm2px(Vec(colTrigIn, y)), module, TR808::CB_TRIG_INPUT));
        addParam(createParamCentered<Trimpot>(mm2px(Vec(colTune, y)), module, TR808::CB_TUNE_PARAM));
        addParam(createParamCentered<Trimpot>(mm2px(Vec(colParam1, y)), module, TR808::CB_DECAY_PARAM));
        addParam(createParamCentered<Trimpot>(mm2px(Vec(colParam2, y)), module, TR808::CB_DETUNE_PARAM));
        addChild(createLightCentered<SmallLight<RedLight>>(mm2px(Vec(colLed, y)), module, TR808::CB_LIGHT));
        addInput(createInputCentered<PJ301MPort>(mm2px(Vec(colTuneCV, y)), module, TR808::CB_TUNE_CV_INPUT));
        addOutput(createOutputCentered<PJ301MPort>(mm2px(Vec(colOut, y)), module, TR808::CB_OUTPUT));

        // === CLOSED HAT (row 6) ===
        y = startY + rowHeight * 6;
        addInput(createInputCentered<PJ301MPort>(mm2px(Vec(colTrigIn, y)), module, TR808::CH_TRIG_INPUT));
        addParam(createParamCentered<Trimpot>(mm2px(Vec(colTune, y)), module, TR808::CH_TUNE_PARAM));
        addParam(createParamCentered<Trimpot>(mm2px(Vec(colParam1, y)), module, TR808::CH_DECAY_PARAM));
        addParam(createParamCentered<Trimpot>(mm2px(Vec(colParam2, y)), module, TR808::CH_SPREAD_PARAM));
        addChild(createLightCentered<SmallLight<RedLight>>(mm2px(Vec(colLed, y)), module, TR808::CH_LIGHT));
        addInput(createInputCentered<PJ301MPort>(mm2px(Vec(colTuneCV, y)), module, TR808::CH_TUNE_CV_INPUT));
        addOutput(createOutputCentered<PJ301MPort>(mm2px(Vec(colOut, y)), module, TR808::CH_OUTPUT));
        addInput(createInputCentered<PJ301MPort>(mm2px(Vec(colParamCV1, y)), module, TR808::CH_SPREAD_CV_INPUT));

        // === OPEN HAT (row 7) ===
        y = startY + rowHeight * 7;
        addInput(createInputCentered<PJ301MPort>(mm2px(Vec(colTrigIn, y)), module, TR808::OH_TRIG_INPUT));
        addParam(createParamCentered<Trimpot>(mm2px(Vec(colTune, y)), module, TR808::OH_TUNE_PARAM));
        addParam(createParamCentered<Trimpot>(mm2px(Vec(colParam1, y)), module, TR808::OH_DECAY_PARAM));
        addParam(createParamCentered<Trimpot>(mm2px(Vec(colParam2, y)), module, TR808::OH_SPREAD_PARAM));
        addChild(createLightCentered<SmallLight<RedLight>>(mm2px(Vec(colLed, y)), module, TR808::OH_LIGHT));
        addInput(createInputCentered<PJ301MPort>(mm2px(Vec(colTuneCV, y)), module, TR808::OH_TUNE_CV_INPUT));
        addOutput(createOutputCentered<PJ301MPort>(mm2px(Vec(colOut, y)), module, TR808::OH_OUTPUT));
        addInput(createInputCentered<PJ301MPort>(mm2px(Vec(colParamCV1, y)), module, TR808::OH_SPREAD_CV_INPUT));

        // === CYMBAL (row 8) ===
        y = startY + rowHeight * 8;
        addInput(createInputCentered<PJ301MPort>(mm2px(Vec(colTrigIn, y)), module, TR808::CY_TRIG_INPUT));
        addParam(createParamCentered<Trimpot>(mm2px(Vec(colTune, y)), module, TR808::CY_TUNE_PARAM));
        addParam(createParamCentered<Trimpot>(mm2px(Vec(colParam1, y)), module, TR808::CY_DECAY_PARAM));
        addParam(createParamCentered<Trimpot>(mm2px(Vec(colParam2, y)), module, TR808::CY_TONE_PARAM));
        addParam(createParamCentered<Trimpot>(mm2px(Vec(colParam3, y)), module, TR808::CY_SPREAD_PARAM));
        addChild(createLightCentered<SmallLight<RedLight>>(mm2px(Vec(colLed, y)), module, TR808::CY_LIGHT));
        addInput(createInputCentered<PJ301MPort>(mm2px(Vec(colTuneCV, y)), module, TR808::CY_TUNE_CV_INPUT));
        addOutput(createOutputCentered<PJ301MPort>(mm2px(Vec(colOut, y)), module, TR808::CY_OUTPUT));

        // === CLAP (row 9) ===
        y = startY + rowHeight * 9;
        addInput(createInputCentered<PJ301MPort>(mm2px(Vec(colTrigIn, y)), module, TR808::CP_TRIG_INPUT));
        addParam(createParamCentered<Trimpot>(mm2px(Vec(colParam1, y)), module, TR808::CP_REVERB_PARAM));
        addParam(createParamCentered<Trimpot>(mm2px(Vec(colParam2, y)), module, TR808::CP_SPREAD_PARAM));
        addParam(createParamCentered<Trimpot>(mm2px(Vec(colParam3, y)), module, TR808::CP_TONE_PARAM));
        addChild(createLightCentered<SmallLight<RedLight>>(mm2px(Vec(colLed, y)), module, TR808::CP_LIGHT));
        addOutput(createOutputCentered<PJ301MPort>(mm2px(Vec(colOut, y)), module, TR808::CP_OUTPUT));

        // === MARACAS (row 10) ===
        y = startY + rowHeight * 10;
        addInput(createInputCentered<PJ301MPort>(mm2px(Vec(colTrigIn, y)), module, TR808::MA_TRIG_INPUT));
        addParam(createParamCentered<Trimpot>(mm2px(Vec(colParam1, y)), module, TR808::MA_DECAY_PARAM));
        addParam(createParamCentered<Trimpot>(mm2px(Vec(colParam2, y)), module, TR808::MA_TONE_PARAM));
        addChild(createLightCentered<SmallLight<RedLight>>(mm2px(Vec(colLed, y)), module, TR808::MA_LIGHT));
        addOutput(createOutputCentered<PJ301MPort>(mm2px(Vec(colOut, y)), module, TR808::MA_OUTPUT));

        // === RIMSHOT (row 11) ===
        y = startY + rowHeight * 11;
        addInput(createInputCentered<PJ301MPort>(mm2px(Vec(colTrigIn, y)), module, TR808::RS_TRIG_INPUT));
        addParam(createParamCentered<Trimpot>(mm2px(Vec(colTune, y)), module, TR808::RS_TUNE_PARAM));
        addParam(createParamCentered<Trimpot>(mm2px(Vec(colParam1, y)), module, TR808::RS_DECAY_PARAM));
        addChild(createLightCentered<SmallLight<RedLight>>(mm2px(Vec(colLed, y)), module, TR808::RS_LIGHT));
        addOutput(createOutputCentered<PJ301MPort>(mm2px(Vec(colOut, y)), module, TR808::RS_OUTPUT));

        // === MASTER SECTION (bottom row) ===
        y = startY + rowHeight * 12 + 2.f;  // Extra spacing for master
        addParam(createParamCentered<RoundBlackKnob>(mm2px(Vec(colTune, y)), module, TR808::MASTER_COMP_PARAM));
        addParam(createParamCentered<RoundBlackKnob>(mm2px(Vec(colParam1, y)), module, TR808::MASTER_GAIN_PARAM));
        addParam(createParamCentered<RoundBlackKnob>(mm2px(Vec(colParam2 + 8, y)), module, TR808::MASTER_TONE_PARAM));
        addOutput(createOutputCentered<PJ301MPort>(mm2px(Vec(colOut, y)), module, TR808::MIX_OUTPUT));

        // Circuit bend params at bottom right
        addParam(createParamCentered<Trimpot>(mm2px(Vec(colParamCV1, y)), module, TR808::BD_DRIVE_PARAM));
        addParam(createParamCentered<Trimpot>(mm2px(Vec(colParamCV2, y)), module, TR808::SD_SNAP_FILTER_PARAM));
    }
};

} // namespace WiggleRoom

Model* modelTR808 = createModel<WiggleRoom::TR808, WiggleRoom::TR808Widget>("TR808");
