/******************************************************************************
 * PLUCKED STRING
 * Karplus-Strong physical model of a plucked string
 * Creates guitar, harp, and plucked instrument sounds
 * Built with Faust DSP
 ******************************************************************************/

#include "rack.hpp"
#include "FaustModule.hpp"
#define FAUST_MODULE_NAME PluckedString
#include "plucked_string.hpp"  // Generated by Faust

using namespace rack;

extern Plugin* pluginInstance;

namespace WiggleRoom {

/**
 * PluckedString - Karplus-Strong Plucked String Synthesizer
 *
 * A physical model that simulates a plucked string using a filtered
 * delay line feedback loop. Creates realistic guitar, harp, and
 * plucked instrument tones.
 *
 * Inputs:
 *   - V/Oct: Pitch control (0V = C4)
 *   - Gate: Trigger input (plucks when > 1V)
 *
 * Parameters:
 *   - Damping: String damping (0 = bright/long, 1 = muted/short)
 *   - Position: Pluck position (0 = bridge, 1 = middle)
 *   - Brightness: Excitation brightness
 */
struct PluckedString : FaustModule<VCVRackDSP> {
    enum ParamId {
        DAMPING_PARAM,
        POSITION_PARAM,
        BRIGHTNESS_PARAM,
        STRENGTH_PARAM,
        CHORUS_PARAM,
        REVERB_PARAM,
        PARAMS_LEN
    };
    enum InputId {
        VOCT_INPUT,
        GATE_INPUT,
        DAMPING_CV_INPUT,
        POSITION_CV_INPUT,
        BRIGHTNESS_CV_INPUT,
        STRENGTH_CV_INPUT,
        REVERB_CV_INPUT,
        INPUTS_LEN
    };
    enum OutputId {
        LEFT_OUTPUT,
        RIGHT_OUTPUT,
        OUTPUTS_LEN
    };
    enum LightId {
        LIGHTS_LEN
    };

    PluckedString() {
        config(PARAMS_LEN, INPUTS_LEN, OUTPUTS_LEN, LIGHTS_LEN);

        // Configure parameters
        configParam(DAMPING_PARAM, 0.0f, 1.0f, 0.3f, "Damping", "%", 0.f, 100.f);
        configParam(POSITION_PARAM, 0.01f, 0.99f, 0.5f, "Position", "%", 0.f, 100.f);
        configParam(BRIGHTNESS_PARAM, 0.0f, 1.0f, 0.5f, "Brightness", "%", 0.f, 100.f);
        configParam(STRENGTH_PARAM, 0.0f, 1.0f, 0.7f, "Strength", "%", 0.f, 100.f);
        configParam(CHORUS_PARAM, 0.0f, 1.0f, 0.3f, "Chorus", "%", 0.f, 100.f);
        configParam(REVERB_PARAM, 0.0f, 1.0f, 0.3f, "Reverb", "%", 0.f, 100.f);

        // Configure inputs
        configInput(VOCT_INPUT, "V/Oct");
        configInput(GATE_INPUT, "Gate");
        configInput(DAMPING_CV_INPUT, "Damping CV");
        configInput(POSITION_CV_INPUT, "Position CV");
        configInput(BRIGHTNESS_CV_INPUT, "Brightness CV");
        configInput(STRENGTH_CV_INPUT, "Strength CV");
        configInput(REVERB_CV_INPUT, "Reverb CV");

        // Configure outputs
        configOutput(LEFT_OUTPUT, "Left");
        configOutput(RIGHT_OUTPUT, "Right");

        // Faust params (alphabetical): brightness=0, chorus=1, damping=2, gate=3, position=4, reverb=5, strength=6, volts=7
        mapParam(BRIGHTNESS_PARAM, 0);
        mapParam(CHORUS_PARAM, 1);
        mapParam(DAMPING_PARAM, 2);
        mapParam(POSITION_PARAM, 4);
        mapParam(REVERB_PARAM, 5);
        mapParam(STRENGTH_PARAM, 6);
    }

    void process(const ProcessArgs& args) override {
        // Initialize DSP on first run
        if (!initialized) {
            faustDsp.init(static_cast<int>(args.sampleRate));
            initialized = true;
        }

        // Get V/Oct and Gate inputs
        float voct = inputs[VOCT_INPUT].getVoltage();
        float gate = inputs[GATE_INPUT].getVoltage();

        // Get damping with CV modulation
        float damping = params[DAMPING_PARAM].getValue();
        if (inputs[DAMPING_CV_INPUT].isConnected()) {
            damping += inputs[DAMPING_CV_INPUT].getVoltage() * 0.1f;  // ±10V = ±1.0
        }
        damping = clamp(damping, 0.f, 1.f);

        // Get position with CV modulation
        float position = params[POSITION_PARAM].getValue();
        if (inputs[POSITION_CV_INPUT].isConnected()) {
            position += inputs[POSITION_CV_INPUT].getVoltage() * 0.1f;  // ±10V = ±1.0
        }
        position = clamp(position, 0.01f, 0.99f);

        // Get brightness with CV modulation
        float brightness = params[BRIGHTNESS_PARAM].getValue();
        if (inputs[BRIGHTNESS_CV_INPUT].isConnected()) {
            brightness += inputs[BRIGHTNESS_CV_INPUT].getVoltage() * 0.1f;  // ±10V = ±1.0
        }
        brightness = clamp(brightness, 0.f, 1.f);

        // Get strength with CV modulation
        float strength = params[STRENGTH_PARAM].getValue();
        if (inputs[STRENGTH_CV_INPUT].isConnected()) {
            strength += inputs[STRENGTH_CV_INPUT].getVoltage() * 0.1f;  // ±10V = ±1.0
        }
        strength = clamp(strength, 0.f, 1.f);

        // Get chorus (no CV for now)
        float chorus = params[CHORUS_PARAM].getValue();

        // Get reverb with CV modulation
        float reverb = params[REVERB_PARAM].getValue();
        if (inputs[REVERB_CV_INPUT].isConnected()) {
            reverb += inputs[REVERB_CV_INPUT].getVoltage() * 0.1f;  // ±10V = ±1.0
        }
        reverb = clamp(reverb, 0.f, 1.f);

        // Update Faust parameters (alphabetical order)
        faustDsp.setParamValue(0, brightness);  // brightness
        faustDsp.setParamValue(1, chorus);      // chorus
        faustDsp.setParamValue(2, damping);     // damping
        faustDsp.setParamValue(3, gate);        // gate
        faustDsp.setParamValue(4, position);    // position
        faustDsp.setParamValue(5, reverb);      // reverb
        faustDsp.setParamValue(6, strength);    // strength
        faustDsp.setParamValue(7, voct);        // volts

        // Process audio (no input, stereo output)
        float* nullInputs[1] = { nullptr };
        float outputL = 0.0f, outputR = 0.0f;
        float* outputPtrs[2] = { &outputL, &outputR };

        faustDsp.compute(1, nullInputs, outputPtrs);

        // Output at 5V peak
        outputs[LEFT_OUTPUT].setVoltage(outputL * 5.0f);
        outputs[RIGHT_OUTPUT].setVoltage(outputR * 5.0f);
    }
};

struct PluckedStringWidget : ModuleWidget {
    PluckedStringWidget(PluckedString* module) {
        setModule(module);
        setPanel(createPanel(asset::plugin(pluginInstance, "res/PluckedString.svg")));

        // Screws
        addChild(createWidget<ScrewSilver>(Vec(RACK_GRID_WIDTH, 0)));
        addChild(createWidget<ScrewSilver>(Vec(box.size.x - 2 * RACK_GRID_WIDTH, 0)));
        addChild(createWidget<ScrewSilver>(Vec(RACK_GRID_WIDTH, RACK_GRID_HEIGHT - RACK_GRID_WIDTH)));
        addChild(createWidget<ScrewSilver>(Vec(box.size.x - 2 * RACK_GRID_WIDTH, RACK_GRID_HEIGHT - RACK_GRID_WIDTH)));

        float xCenter = box.size.x / 2.0f;
        float xLeft = 25;
        float xRight = box.size.x - 25;

        // Damping and Strength knobs at top (big knobs)
        addParam(createParamCentered<RoundBigBlackKnob>(
            Vec(xLeft, 55), module, PluckedString::DAMPING_PARAM));
        addParam(createParamCentered<RoundBigBlackKnob>(
            Vec(xRight, 55), module, PluckedString::STRENGTH_PARAM));

        // Position and Brightness knobs
        addParam(createParamCentered<RoundSmallBlackKnob>(
            Vec(xLeft, 102), module, PluckedString::POSITION_PARAM));
        addParam(createParamCentered<RoundSmallBlackKnob>(
            Vec(xRight, 102), module, PluckedString::BRIGHTNESS_PARAM));

        // Chorus and Reverb knobs
        addParam(createParamCentered<RoundSmallBlackKnob>(
            Vec(xLeft, 145), module, PluckedString::CHORUS_PARAM));
        addParam(createParamCentered<RoundSmallBlackKnob>(
            Vec(xRight, 145), module, PluckedString::REVERB_PARAM));

        // CV Inputs (2 rows of 2)
        addInput(createInputCentered<PJ301MPort>(
            Vec(xLeft, 195), module, PluckedString::DAMPING_CV_INPUT));
        addInput(createInputCentered<PJ301MPort>(
            Vec(xRight, 195), module, PluckedString::STRENGTH_CV_INPUT));
        addInput(createInputCentered<PJ301MPort>(
            Vec(xLeft, 230), module, PluckedString::POSITION_CV_INPUT));
        addInput(createInputCentered<PJ301MPort>(
            Vec(xRight, 230), module, PluckedString::BRIGHTNESS_CV_INPUT));

        // V/Oct and Gate inputs
        addInput(createInputCentered<PJ301MPort>(
            Vec(xLeft, 270), module, PluckedString::VOCT_INPUT));
        addInput(createInputCentered<PJ301MPort>(
            Vec(xRight, 270), module, PluckedString::GATE_INPUT));

        // Stereo Outputs
        addOutput(createOutputCentered<PJ301MPort>(
            Vec(xLeft, 315), module, PluckedString::LEFT_OUTPUT));
        addOutput(createOutputCentered<PJ301MPort>(
            Vec(xRight, 315), module, PluckedString::RIGHT_OUTPUT));
    }
};

} // namespace WiggleRoom

Model* modelPluckedString = createModel<WiggleRoom::PluckedString, WiggleRoom::PluckedStringWidget>("PluckedString");
