/******************************************************************************
 * ACID9Voice
 * TB-303 inspired acid synthesizer voice with modern enhancements
 *
 * Features:
 * - Tri-core morphing oscillator (saw/sharktooth/square)
 * - ISOTOPE detune/stereo spread control
 * - Sub oscillator (sine/square)
 * - Pre-filter GRIT saturation
 * - Dual filters (ACID diode ladder / LEAD OTA)
 * - Filter envelope with accent boost
 * - Insert loop (send/return)
 * - Stereo delay with clock sync and ghost mode
 * - Slide (portamento) control
 *
 * Part of the WiggleRoom VCV Rack plugin
 ******************************************************************************/

#include "rack.hpp"
#include "FaustModule.hpp"
#define FAUST_MODULE_NAME ACID9Voice
#include "acid9voice.hpp"  // Generated by Faust

using namespace rack;

extern Plugin* pluginInstance;

namespace WiggleRoom {

/**
 * ACID9Voice - TB-303 Inspired Acid Synthesizer Voice
 *
 * A modern take on the classic acid sound with extended capabilities.
 *
 * Signal Flow:
 *   Tri-Core Osc + Sub -> Grit -> Filter -> VCA -> Insert Loop -> Delay -> Output
 *
 * Inputs:
 *   - V/OCT: Pitch control (0V = C4)
 *   - GATE: Note on/off
 *   - ACCENT: Boosts filter env and VCA
 *   - SLIDE: Enables portamento when high
 *   - CUTOFF_CV: Filter cutoff modulation
 *   - FM_IN: Frequency modulation
 *   - CLOCK: Clock for delay sync
 *   - RETURN: Insert loop return (normalizes to send when unpatched)
 *   - SHAPE_CV: Shape (waveform morph) modulation
 *   - ISOTOPE_CV: Isotope (detune/spread) modulation
 *   - DECAY_CV: Decay (filter envelope) modulation
 *
 * Outputs:
 *   - LEFT/RIGHT: Main stereo output
 *   - SEND: Insert loop send (post-VCA, pre-delay)
 */
struct ACID9Voice : FaustModule<VCVRackDSP> {
    enum ParamId {
        // Oscillator section
        SHAPE_PARAM,
        ISOTOPE_PARAM,
        SUB_LEVEL_PARAM,
        SUB_MODE_PARAM,
        // Filter section
        CUTOFF_PARAM,
        RESONANCE_PARAM,
        ENV_MOD_PARAM,
        DECAY_PARAM,
        FILTER_MODE_PARAM,
        GRIT_PARAM,
        // Delay section
        DELAY_TIME_PARAM,
        DELAY_FB_PARAM,
        DELAY_MIX_PARAM,
        DELAY_RATIO_PARAM,
        DELAY_GHOST_PARAM,
        PARAMS_LEN
    };
    enum InputId {
        VOCT_INPUT,
        GATE_INPUT,
        ACCENT_INPUT,
        SLIDE_INPUT,
        CUTOFF_CV_INPUT,
        FM_INPUT,
        CLOCK_INPUT,
        RETURN_INPUT,
        SHAPE_CV_INPUT,
        ISOTOPE_CV_INPUT,
        DECAY_CV_INPUT,
        INPUTS_LEN
    };
    enum OutputId {
        LEFT_OUTPUT,
        RIGHT_OUTPUT,
        SEND_OUTPUT,
        OUTPUTS_LEN
    };
    enum LightId {
        FILTER_MODE_LIGHT,  // Shows ACID (off) / LEAD (on)
        LIGHTS_LEN
    };

    // Clock tracking for delay sync
    float lastClockVoltage = 0.f;
    float clockPeriodSamples = 0.f;
    float samplesSinceLastClock = 0.f;
    bool clockSynced = false;
    bool haveClockEdge = false;
    float currentSampleRate = 48000.f;

    void clearClock() {
        lastClockVoltage = 0.f;
        clockPeriodSamples = samplesSinceLastClock = 0.f;
        clockSynced = haveClockEdge = false;
    }
    void onSampleRateChange(const SampleRateChangeEvent& e) override {
        currentSampleRate = e.sampleRate;
        FaustModule<VCVRackDSP>::onSampleRateChange(e);
        clearClock();
    }
    void onReset(const ResetEvent& e) override {
        Module::onReset(e);
        faustDsp.init(static_cast<int>(currentSampleRate));
        initialized = true;
        clearClock();
    }
    static float finiteVoltage(float value, float low, float high) {
        return std::isfinite(value) ? clamp(value, low, high) : 0.f;
    }

    ACID9Voice() {
        config(PARAMS_LEN, INPUTS_LEN, OUTPUTS_LEN, LIGHTS_LEN);

        // Oscillator section
        configParam(SHAPE_PARAM, 0.f, 1.f, 0.f, "Shape", "", 0.f, 100.f);
        configParam(ISOTOPE_PARAM, 0.f, 1.f, 0.f, "Isotope", "%", 0.f, 100.f);
        configParam(SUB_LEVEL_PARAM, 0.f, 1.f, 0.f, "Sub Level", "%", 0.f, 100.f);
        configSwitch(SUB_MODE_PARAM, 0.f, 1.f, 0.f, "Sub Mode", {"Sine", "Square"});

        // Filter section
        configParam(CUTOFF_PARAM, 20.f, 20000.f, 1000.f, "Cutoff", " Hz");
        configParam(RESONANCE_PARAM, 0.f, 1.f, 0.3f, "Resonance", "%", 0.f, 100.f);
        configParam(ENV_MOD_PARAM, -1.f, 1.f, 0.5f, "Env Mod", "%", 0.f, 100.f);
        configParam(DECAY_PARAM, 0.01f, 2.f, 0.3f, "Decay", " s");
        configSwitch(FILTER_MODE_PARAM, 0.f, 1.f, 0.f, "Filter Mode", {"ACID", "LEAD"});
        configParam(GRIT_PARAM, 0.f, 1.f, 0.f, "Grit", "%", 0.f, 100.f);

        // Delay section
        configParam(DELAY_TIME_PARAM, 10.f, 2000.f, 250.f, "Delay Time", " ms");
        configParam(DELAY_FB_PARAM, 0.f, 0.95f, 0.3f, "Delay Feedback", "%", 0.f, 105.26f);
        configParam(DELAY_MIX_PARAM, 0.f, 1.f, 0.f, "Delay Mix", "%", 0.f, 100.f);
        configSwitch(DELAY_RATIO_PARAM, 0.f, 4.f, 2.f, "Delay Ratio", {"/4", "/2", "x1", "x2", "x4"});
        configParam(DELAY_GHOST_PARAM, 0.f, 1.f, 0.f, "Ghost", "%", 0.f, 100.f);

        // Inputs
        configInput(VOCT_INPUT, "V/Oct");
        configInput(GATE_INPUT, "Gate");
        configInput(ACCENT_INPUT, "Accent");
        configInput(SLIDE_INPUT, "Slide");
        configInput(CUTOFF_CV_INPUT, "Cutoff CV");
        configInput(FM_INPUT, "FM");
        configInput(CLOCK_INPUT, "Clock");
        configInput(RETURN_INPUT, "Insert Return");
        configInput(SHAPE_CV_INPUT, "Shape CV");
        configInput(ISOTOPE_CV_INPUT, "Isotope CV");
        configInput(DECAY_CV_INPUT, "Decay CV");

        // Outputs
        configOutput(LEFT_OUTPUT, "Left");
        configOutput(RIGHT_OUTPUT, "Right");
        configOutput(SEND_OUTPUT, "Insert Send");

        // Light
        configLight(FILTER_MODE_LIGHT, "Filter Mode (ACID/LEAD)");

        // Faust parameter indices (ALPHABETICAL ORDER):
        // NOTE: delay_ratio was optimized out by Faust (defined but unused)
        // accent=0, cutoff=1, cutoff_cv=2, decay=3, delay_fb=4, delay_ghost=5,
        // delay_mix=6, delay_time=7, env_mod=8, filter_mode=9, fm_in=10,
        // gate=11, grit=12, isotope=13, resonance=14, return_connected=15,
        // return_in_l=16, return_in_r=17, shape=18, slide=19, sub_level=20,
        // sub_mode=21, volts=22

        // Map VCV params to Faust params (not using mapParam for complex CV handling)
    }

    void process(const ProcessArgs& args) override {
        // Initialize DSP on first run
        if (!initialized) {
            currentSampleRate = args.sampleRate;
            faustDsp.init(static_cast<int>(args.sampleRate));
            initialized = true;
        }

        // Clock tracking for delay sync
        float clockVoltage = finiteVoltage(inputs[CLOCK_INPUT].getVoltage(), -20.f, 20.f);
        if (!inputs[CLOCK_INPUT].isConnected()) clearClock();
        bool clockRising = (clockVoltage > 0.5f) && (lastClockVoltage <= 0.5f);
        lastClockVoltage = clockVoltage;

        if (clockRising) {
            if (haveClockEdge && samplesSinceLastClock > 100.f) {  // Ignore very short periods
                clockPeriodSamples = samplesSinceLastClock;
                clockSynced = true;
            }
            samplesSinceLastClock = 0.f;
            haveClockEdge = true;
        }
        samplesSinceLastClock += 1.f;

        // Decay clock sync if no clock received
        if (samplesSinceLastClock > args.sampleRate * 2.f) {
            clockSynced = false;
            haveClockEdge = false;
        }

        // Get inputs
        float voct = finiteVoltage(inputs[VOCT_INPUT].getVoltage(), -5.f, 10.f);
        float gate = finiteVoltage(inputs[GATE_INPUT].getVoltage(), 0.f, 10.f);
        float accent = finiteVoltage(inputs[ACCENT_INPUT].getVoltage(), 0.f, 10.f);
        float slide = finiteVoltage(inputs[SLIDE_INPUT].getVoltage(), 0.f, 10.f);
        float cutoffCV = finiteVoltage(inputs[CUTOFF_CV_INPUT].getVoltage(), -5.f, 5.f);
        float fmIn = finiteVoltage(inputs[FM_INPUT].getVoltage(), -5.f, 5.f);

        // Insert return (mono for now, could be stereo)
        float returnL = finiteVoltage(inputs[RETURN_INPUT].getVoltage(), -50.f, 50.f) * 0.2f;  // Convert to ±1
        float returnR = returnL;
        float returnConnected = inputs[RETURN_INPUT].isConnected() ? 1.f : 0.f;

        // Get parameter values
        float shape = params[SHAPE_PARAM].getValue();
        float isotope = params[ISOTOPE_PARAM].getValue();
        float subLevel = params[SUB_LEVEL_PARAM].getValue();
        float subMode = params[SUB_MODE_PARAM].getValue();

        float cutoff = params[CUTOFF_PARAM].getValue();
        float resonance = params[RESONANCE_PARAM].getValue();
        float envMod = params[ENV_MOD_PARAM].getValue();
        float decay = params[DECAY_PARAM].getValue();
        float filterMode = params[FILTER_MODE_PARAM].getValue();
        float grit = params[GRIT_PARAM].getValue();

        // Apply CV modulation to shape, isotope, and decay
        // Shape: 0-1 range, ±5V maps to ±0.5 (half range modulation)
        float shapeFinal = clamp(shape + finiteVoltage(inputs[SHAPE_CV_INPUT].getVoltage(), -20.f, 20.f) / 10.f, 0.f, 1.f);
        // Isotope: 0-1 range, ±5V maps to ±0.5 (half range modulation)
        float isotopeFinal = clamp(isotope + finiteVoltage(inputs[ISOTOPE_CV_INPUT].getVoltage(), -20.f, 20.f) / 10.f, 0.f, 1.f);
        // Decay: 0.01-2.0 range, ±5V maps to ±1.0s modulation
        float decayFinal = clamp(decay + finiteVoltage(inputs[DECAY_CV_INPUT].getVoltage(), -20.f, 20.f) / 5.f, 0.01f, 2.f);

        float delayTime = params[DELAY_TIME_PARAM].getValue();
        float delayFb = params[DELAY_FB_PARAM].getValue();
        float delayMix = params[DELAY_MIX_PARAM].getValue();
        float delayRatio = params[DELAY_RATIO_PARAM].getValue();
        float delayGhost = params[DELAY_GHOST_PARAM].getValue();

        // Calculate delay time (sync or manual)
        float actualDelayTime = delayTime;
        if (clockSynced && clockPeriodSamples > 0.f) {
            // Convert ratio index to multiplier
            float ratioMult = 1.f;
            switch (static_cast<int>(delayRatio)) {
                case 0: ratioMult = 0.25f; break;
                case 1: ratioMult = 0.5f; break;
                case 2: ratioMult = 1.f; break;
                case 3: ratioMult = 2.f; break;
                case 4: ratioMult = 4.f; break;
            }
            actualDelayTime = (clockPeriodSamples * ratioMult / args.sampleRate) * 1000.f;
            actualDelayTime = clamp(actualDelayTime, 10.f, 2000.f);
        }

        // Set Faust parameters (alphabetical order - delay_ratio optimized out!)
        faustDsp.setParamValue(0, accent);           // accent
        faustDsp.setParamValue(1, cutoff);           // cutoff
        faustDsp.setParamValue(2, cutoffCV);         // cutoff_cv
        faustDsp.setParamValue(3, decayFinal);        // decay (with CV)
        faustDsp.setParamValue(4, delayFb);          // delay_fb
        faustDsp.setParamValue(5, delayGhost);       // delay_ghost
        faustDsp.setParamValue(6, delayMix);         // delay_mix
        faustDsp.setParamValue(7, actualDelayTime);  // delay_time
        faustDsp.setParamValue(8, envMod);           // env_mod
        faustDsp.setParamValue(9, filterMode);       // filter_mode
        faustDsp.setParamValue(10, fmIn);            // fm_in
        faustDsp.setParamValue(11, gate);            // gate
        faustDsp.setParamValue(12, grit);            // grit
        faustDsp.setParamValue(13, isotopeFinal);     // isotope (with CV)
        faustDsp.setParamValue(14, resonance);       // resonance
        faustDsp.setParamValue(15, returnConnected); // return_connected
        faustDsp.setParamValue(16, returnL);         // return_in_l
        faustDsp.setParamValue(17, returnR);         // return_in_r
        faustDsp.setParamValue(18, shapeFinal);       // shape (with CV)
        faustDsp.setParamValue(19, slide);           // slide
        faustDsp.setParamValue(20, subLevel);        // sub_level
        faustDsp.setParamValue(21, subMode);         // sub_mode
        faustDsp.setParamValue(22, voct);            // volts

        // Process audio (no input, 3 outputs: L, R, Send)
        float* nullInputs[1] = { nullptr };
        float outputL = 0.0f, outputR = 0.0f, outputSend = 0.0f;
        float* outputPtrs[3] = { &outputL, &outputR, &outputSend };

        faustDsp.compute(1, nullInputs, outputPtrs);

        // Output at 5V peak
        outputs[LEFT_OUTPUT].setVoltage(outputL * 5.0f);
        outputs[RIGHT_OUTPUT].setVoltage(outputR * 5.0f);
        outputs[SEND_OUTPUT].setVoltage(outputSend * 5.0f);

        // Update filter mode light
        lights[FILTER_MODE_LIGHT].setBrightness(filterMode);
    }
};

// Rack's shared image cache owns the texture and handles graphics-context changes.
struct ACID9Panel : widget::OpaqueWidget {
    std::shared_ptr<rack::window::Image> artwork;
    std::shared_ptr<rack::window::Svg> labels;
    ACID9Panel() {
        box.size = Vec(510, 380);
        if (APP->window) {
            artwork = APP->window->loadImage(asset::plugin(pluginInstance, "res/ACID9Voice.png"));
            labels = APP->window->loadSvg(asset::plugin(pluginInstance, "res/ACID9Voice-labels.svg"));
        }
    }
    void draw(const DrawArgs& args) override {
        nvgBeginPath(args.vg);
        nvgRect(args.vg, 0, 0, box.size.x, box.size.y);
        nvgFillColor(args.vg, nvgRGB(20, 16, 30));
        nvgFill(args.vg);
        if (artwork && artwork->handle >= 0) {
            nvgFillPaint(args.vg, nvgImagePattern(args.vg, 0, 0, box.size.x, box.size.y, 0, artwork->handle, 1));
            nvgFill(args.vg);
        }
        if (labels) rack::window::svgDraw(args.vg, labels->handle);
        OpaqueWidget::draw(args);
    }
};

struct ACID9VoiceWidget : ModuleWidget {
    ACID9VoiceWidget(ACID9Voice* module) {
        setModule(module);
        box.size = Vec(34 * RACK_GRID_WIDTH, RACK_GRID_HEIGHT);
        addChild(new ACID9Panel());
        addChild(createWidget<ScrewSilver>(Vec(5, 3)));
        addChild(createWidget<ScrewSilver>(Vec(490, 3)));
        addChild(createWidget<ScrewSilver>(Vec(5, 362)));
        addChild(createWidget<ScrewSilver>(Vec(490, 362)));
        auto* p0 = createParamCentered<RoundBigBlackKnob>(Vec(45, 92), module, 0);
        addParam(p0);
        auto* p1 = createParamCentered<RoundBigBlackKnob>(Vec(125, 92), module, 1);
        addParam(p1);
        auto* p2 = createParamCentered<RoundSmallBlackKnob>(Vec(45, 155), module, 2);
        addParam(p2);
        auto* p3 = createParamCentered<CKSS>(Vec(125, 155), module, 3);
        addParam(p3);
        auto* p4 = createParamCentered<RoundBigBlackKnob>(Vec(215, 92), module, 4);
        addParam(p4);
        auto* p5 = createParamCentered<RoundSmallBlackKnob>(Vec(295, 92), module, 5);
        addParam(p5);
        auto* p6 = createParamCentered<RoundSmallBlackKnob>(Vec(215, 155), module, 6);
        addParam(p6);
        auto* p7 = createParamCentered<RoundSmallBlackKnob>(Vec(295, 155), module, 7);
        addParam(p7);
        auto* p9 = createParamCentered<RoundSmallBlackKnob>(Vec(215, 211), module, 9);
        addParam(p9);
        auto* p8 = createParamCentered<CKSS>(Vec(295, 211), module, 8);
        addParam(p8);
        auto* p10 = createParamCentered<RoundBlackKnob>(Vec(385, 92), module, 10);
        addParam(p10);
        auto* p11 = createParamCentered<RoundSmallBlackKnob>(Vec(465, 92), module, 11);
        addParam(p11);
        auto* p12 = createParamCentered<RoundSmallBlackKnob>(Vec(385, 155), module, 12);
        addParam(p12);
        auto* p14 = createParamCentered<RoundSmallBlackKnob>(Vec(465, 155), module, 14);
        addParam(p14);
        auto* p13 = createParamCentered<RoundSmallBlackKnob>(Vec(425, 211), module, 13);
        p13->snap = true;
        addParam(p13);
        addInput(createInputCentered<PJ301MPort>(Vec(45, 320), module, 0));
        addInput(createInputCentered<PJ301MPort>(Vec(125, 320), module, 1));
        addInput(createInputCentered<PJ301MPort>(Vec(205, 320), module, 2));
        addInput(createInputCentered<PJ301MPort>(Vec(285, 320), module, 3));
        addInput(createInputCentered<PJ301MPort>(Vec(215, 270), module, 4));
        addInput(createInputCentered<PJ301MPort>(Vec(45, 211), module, 5));
        addInput(createInputCentered<PJ301MPort>(Vec(385, 270), module, 6));
        addInput(createInputCentered<PJ301MPort>(Vec(465, 270), module, 7));
        addInput(createInputCentered<PJ301MPort>(Vec(45, 270), module, 8));
        addInput(createInputCentered<PJ301MPort>(Vec(125, 270), module, 9));
        addInput(createInputCentered<PJ301MPort>(Vec(295, 270), module, 10));
        addOutput(createOutputCentered<PJ301MPort>(Vec(365, 320), module, 0));
        addOutput(createOutputCentered<PJ301MPort>(Vec(425, 320), module, 1));
        addOutput(createOutputCentered<PJ301MPort>(Vec(485, 320), module, 2));
        addChild(createLightCentered<SmallLight<GreenLight>>(Vec(310, 211), module, ACID9Voice::FILTER_MODE_LIGHT));
    }
};

} // namespace WiggleRoom

Model* modelACID9Voice = createModel<WiggleRoom::ACID9Voice, WiggleRoom::ACID9VoiceWidget>("ACID9Voice");
