/******************************************************************************
 * TETANUS COIL
 * Extreme dispersive spring reverb with non-linear feedback
 * Built with Faust DSP
 ******************************************************************************/

#include "rack.hpp"
#include "FaustModule.hpp"
#include "ImagePanel.hpp"
#define FAUST_MODULE_NAME TetanusCoil
#include "tetanus_coil.hpp"  // Generated by Faust

using namespace rack;

extern Plugin* pluginInstance;

namespace WiggleRoom {

/**
 * TetanusCoil - Extreme Spring Reverb
 *
 * Physical model of spring coils with dispersion and non-linear feedback.
 * Creates the classic "drippy" spring sound that can be pushed into
 * screaming chaos.
 *
 * Parameters:
 *   - Feedback: Recirculation amount (0-0.99)
 *   - Tension: Coil delay length affecting pitch (1-500)
 *   - Darkness: Lowpass cutoff for damping (200-18000Hz)
 *   - Wobble: LFO modulation depth (0-5)
 *   - Grit: Distortion inside feedback loop (0-10)
 *   - Kick: Button/trigger to inject noise burst
 */
struct TetanusCoil : FaustModule<VCVRackDSP> {
    enum ParamId {
        FEEDBACK_PARAM,
        TENSION_PARAM,
        DARKNESS_PARAM,
        WOBBLE_PARAM,
        GRIT_PARAM,
        KICK_PARAM,  // Momentary button
        PARAMS_LEN
    };
    enum InputId {
        AUDIO_INPUT,
        FEEDBACK_CV_INPUT,
        GRIT_CV_INPUT,
        KICK_TRIG_INPUT,
        INPUTS_LEN
    };
    enum OutputId {
        LEFT_OUTPUT,
        RIGHT_OUTPUT,
        OUTPUTS_LEN
    };
    enum LightId {
        KICK_LIGHT,
        LIGHTS_LEN
    };

    // For kick button/trigger handling
    dsp::SchmittTrigger kickTrigger;
    dsp::PulseGenerator kickPulse;

    TetanusCoil() {
        config(PARAMS_LEN, INPUTS_LEN, OUTPUTS_LEN, LIGHTS_LEN);

        // Configure parameters
        configParam(FEEDBACK_PARAM, 0.f, 0.99f, 0.9f, "Feedback", "%", 0.f, 100.f);
        configParam(TENSION_PARAM, 1.f, 500.f, 100.f, "Coil Tension");
        configParam(DARKNESS_PARAM, 200.f, 18000.f, 5000.f, "Darkness", " Hz");
        configParam(WOBBLE_PARAM, 0.f, 5.f, 0.1f, "Wobble");
        configParam(GRIT_PARAM, 0.f, 10.f, 0.f, "Grit");
        configButton(KICK_PARAM, "Kick the Amp");

        // Configure inputs
        configInput(AUDIO_INPUT, "Audio");
        configInput(FEEDBACK_CV_INPUT, "Feedback CV");
        configInput(GRIT_CV_INPUT, "Grit CV");
        configInput(KICK_TRIG_INPUT, "Kick Trigger");

        // Configure outputs
        configOutput(LEFT_OUTPUT, "Left");
        configOutput(RIGHT_OUTPUT, "Right");

        // Faust params are alphabetical: darkness=0, feedback=1, grit=2, kick=3, tension=4, wobble=5
        // We don't use mapParam here since we need custom CV handling
    }

    void process(const ProcessArgs& args) override {
        // Initialize DSP on first run
        if (!initialized) {
            faustDsp.init(static_cast<int>(args.sampleRate));
            initialized = true;
        }

        // Handle kick button and trigger input
        bool kickPressed = params[KICK_PARAM].getValue() > 0.5f;
        bool kickTriggered = false;

        if (inputs[KICK_TRIG_INPUT].isConnected()) {
            kickTriggered = kickTrigger.process(inputs[KICK_TRIG_INPUT].getVoltage(), 0.1f, 2.f);
        }

        if (kickPressed || kickTriggered) {
            kickPulse.trigger(0.1f);  // 100ms pulse
        }

        float kickValue = kickPulse.process(args.sampleTime) ? 10.f : 0.f;
        lights[KICK_LIGHT].setBrightness(kickValue > 0.f ? 1.f : 0.f);

        // Get parameter values with CV modulation
        float feedbackVal = params[FEEDBACK_PARAM].getValue();
        if (inputs[FEEDBACK_CV_INPUT].isConnected()) {
            feedbackVal += inputs[FEEDBACK_CV_INPUT].getVoltage() * 0.099f;  // 10V = full range
        }
        feedbackVal = clamp(feedbackVal, 0.f, 0.99f);

        float gritVal = params[GRIT_PARAM].getValue();
        if (inputs[GRIT_CV_INPUT].isConnected()) {
            gritVal += inputs[GRIT_CV_INPUT].getVoltage();  // 10V = +10 grit
        }
        gritVal = clamp(gritVal, 0.f, 10.f);

        // Set Faust parameters (alphabetical order)
        faustDsp.setParamValue(0, params[DARKNESS_PARAM].getValue());  // darkness
        faustDsp.setParamValue(1, feedbackVal);                         // feedback (with CV)
        faustDsp.setParamValue(2, gritVal);                             // grit (with CV)
        faustDsp.setParamValue(3, kickValue);                           // kick
        faustDsp.setParamValue(4, params[TENSION_PARAM].getValue());   // tension
        faustDsp.setParamValue(5, params[WOBBLE_PARAM].getValue());    // wobble

        // Get audio input (mono to stereo if only one channel)
        float inputL = inputs[AUDIO_INPUT].getVoltage() * 0.2f;  // 5V -> 1.0
        float inputR = inputL;  // Mono input duplicated to stereo

        float* inputPtrs[2] = { &inputL, &inputR };
        float outputL = 0.0f, outputR = 0.0f;
        float* outputPtrs[2] = { &outputL, &outputR };

        // Process audio
        faustDsp.compute(1, inputPtrs, outputPtrs);

        // Output (back to VCV voltage range)
        outputs[LEFT_OUTPUT].setVoltage(outputL * 5.0f);
        outputs[RIGHT_OUTPUT].setVoltage(outputR * 5.0f);
    }
};

struct TetanusCoilWidget : ModuleWidget {
    TetanusCoilWidget(TetanusCoil* module) {
        setModule(module);
        box.size = Vec(8 * RACK_GRID_WIDTH, RACK_GRID_HEIGHT);
        addChild(new WiggleRoom::ImagePanel(
            asset::plugin(pluginInstance, "res/TetanusCoil.png"), box.size));

        // Screws
        addChild(createWidget<ScrewSilver>(Vec(RACK_GRID_WIDTH, 0)));
        addChild(createWidget<ScrewSilver>(Vec(box.size.x - 2 * RACK_GRID_WIDTH, 0)));
        addChild(createWidget<ScrewSilver>(Vec(RACK_GRID_WIDTH, RACK_GRID_HEIGHT - RACK_GRID_WIDTH)));
        addChild(createWidget<ScrewSilver>(Vec(box.size.x - 2 * RACK_GRID_WIDTH, RACK_GRID_HEIGHT - RACK_GRID_WIDTH)));

        float xCenter = box.size.x / 2.0f;
        float xLeft = xCenter - 25.f;
        float xRight = xCenter + 25.f;

        // Row 1: Feedback & Tension (big knobs)
        addParam(createParamCentered<RoundBigBlackKnob>(
            Vec(xLeft, 55), module, TetanusCoil::FEEDBACK_PARAM));
        addParam(createParamCentered<RoundBigBlackKnob>(
            Vec(xRight, 55), module, TetanusCoil::TENSION_PARAM));

        // Row 2: Darkness & Wobble
        addParam(createParamCentered<RoundBlackKnob>(
            Vec(xLeft, 110), module, TetanusCoil::DARKNESS_PARAM));
        addParam(createParamCentered<RoundBlackKnob>(
            Vec(xRight, 110), module, TetanusCoil::WOBBLE_PARAM));

        // Row 3: Grit (center, big) with light
        addParam(createParamCentered<RoundBigBlackKnob>(
            Vec(xCenter, 160), module, TetanusCoil::GRIT_PARAM));

        // Row 4: KICK button with light
        addParam(createParamCentered<VCVButton>(
            Vec(xCenter, 210), module, TetanusCoil::KICK_PARAM));
        addChild(createLightCentered<MediumLight<RedLight>>(
            Vec(xCenter + 15, 210), module, TetanusCoil::KICK_LIGHT));

        // Row 5: CV Inputs
        addInput(createInputCentered<PJ301MPort>(
            Vec(xLeft, 255), module, TetanusCoil::FEEDBACK_CV_INPUT));
        addInput(createInputCentered<PJ301MPort>(
            Vec(xCenter, 255), module, TetanusCoil::GRIT_CV_INPUT));
        addInput(createInputCentered<PJ301MPort>(
            Vec(xRight, 255), module, TetanusCoil::KICK_TRIG_INPUT));

        // Row 6: Audio Input (center)
        addInput(createInputCentered<PJ301MPort>(
            Vec(xCenter, 295), module, TetanusCoil::AUDIO_INPUT));

        // Row 7: Stereo Outputs
        addOutput(createOutputCentered<PJ301MPort>(
            Vec(xLeft, 335), module, TetanusCoil::LEFT_OUTPUT));
        addOutput(createOutputCentered<PJ301MPort>(
            Vec(xRight, 335), module, TetanusCoil::RIGHT_OUTPUT));
    }
};

} // namespace WiggleRoom

Model* modelTetanusCoil = createModel<WiggleRoom::TetanusCoil, WiggleRoom::TetanusCoilWidget>("TetanusCoil");
