/******************************************************************************
 * LADDER LPF
 * Classic ladder lowpass filter with resonance
 * Built with Faust DSP
 ******************************************************************************/

#include "rack.hpp"
#include "FaustModule.hpp"
#include "ImagePanel.hpp"
#define FAUST_MODULE_NAME LadderLPF
#include "ladder_lpf.hpp"  // Generated by Faust from ladder_lpf.dsp

using namespace rack;

extern Plugin* pluginInstance;

namespace WiggleRoom {

/**
 * LadderLPF - Ladder Lowpass Filter
 *
 * A classic 4-pole resonant lowpass filter.
 * Uses Faust DSP for the filter algorithm.
 *
 * Inputs:
 *   - Audio In: Signal to filter
 *   - Cutoff CV: V/Oct modulation of cutoff frequency
 *   - Resonance CV: Linear modulation of resonance
 *
 * Parameters:
 *   - Cutoff: Filter cutoff frequency (20Hz - 20kHz)
 *   - Resonance: Filter resonance (0 - 0.95)
 */
struct LadderLPF : FaustModule<VCVRackDSP> {
    enum ParamId {
        CUTOFF_PARAM,
        RESONANCE_PARAM,
        PARAMS_LEN
    };
    enum InputId {
        AUDIO_INPUT,
        CUTOFF_CV_INPUT,
        RESONANCE_CV_INPUT,
        INPUTS_LEN
    };
    enum OutputId {
        AUDIO_OUTPUT,
        OUTPUTS_LEN
    };
    enum LightId {
        LIGHTS_LEN
    };

    LadderLPF() {
        config(PARAMS_LEN, INPUTS_LEN, OUTPUTS_LEN, LIGHTS_LEN);

        // Configure parameters
        // Cutoff: 20Hz to 20kHz, logarithmic response, default 1kHz
        configParam(CUTOFF_PARAM, 20.0f, 20000.0f, 1000.0f, "Cutoff", " Hz");

        // Resonance: 0 to 0.95 (near 1.0 causes self-oscillation)
        configParam(RESONANCE_PARAM, 0.0f, 0.95f, 0.0f, "Resonance");

        // Configure inputs
        configInput(AUDIO_INPUT, "Audio");
        configInput(CUTOFF_CV_INPUT, "Cutoff CV (V/Oct)");
        configInput(RESONANCE_CV_INPUT, "Resonance CV");

        // Configure output
        configOutput(AUDIO_OUTPUT, "Filtered Audio");

        // Set audio I/O for the base class
        setAudioIO(AUDIO_INPUT, AUDIO_OUTPUT);

        // Map VCV parameters to Faust DSP parameters
        // Faust params are indexed in order of declaration in .dsp:
        //   0 = cutoff
        //   1 = resonance
        mapParam(CUTOFF_PARAM, 0);      // Cutoff knob -> Faust param 0
        mapParam(RESONANCE_PARAM, 1);   // Resonance knob -> Faust param 1

        // Map CV inputs to modulate Faust parameters
        // Cutoff CV uses V/Oct exponential scaling (1V = 1 octave up)
        mapCVInput(CUTOFF_CV_INPUT, 0, true, 1.0f);

        // Resonance CV uses bipolar linear modulation (+/-10V adds +/-0.95)
        mapCVInput(RESONANCE_CV_INPUT, 1, false, 0.095f);
    }
};

struct LadderLPFWidget : ModuleWidget {
    LadderLPFWidget(LadderLPF* module) {
        setModule(module);
        box.size = Vec(4 * RACK_GRID_WIDTH, RACK_GRID_HEIGHT);
        addChild(new WiggleRoom::ImagePanel(
            asset::plugin(pluginInstance, "res/LadderLPF.png"), box.size));

        // Screws
        addChild(createWidget<ScrewSilver>(Vec(RACK_GRID_WIDTH, 0)));
        addChild(createWidget<ScrewSilver>(Vec(box.size.x - 2 * RACK_GRID_WIDTH, 0)));
        addChild(createWidget<ScrewSilver>(Vec(RACK_GRID_WIDTH, RACK_GRID_HEIGHT - RACK_GRID_WIDTH)));
        addChild(createWidget<ScrewSilver>(Vec(box.size.x - 2 * RACK_GRID_WIDTH, RACK_GRID_HEIGHT - RACK_GRID_WIDTH)));

        float xCenter = box.size.x / 2.0f;

        // Main Cutoff knob (large, prominent)
        addParam(createParamCentered<RoundBigBlackKnob>(
            Vec(xCenter, 70), module, LadderLPF::CUTOFF_PARAM));

        // Resonance knob
        addParam(createParamCentered<RoundBlackKnob>(
            Vec(xCenter, 140), module, LadderLPF::RESONANCE_PARAM));

        // CV Inputs
        addInput(createInputCentered<PJ301MPort>(
            Vec(xCenter - 25, 200), module, LadderLPF::CUTOFF_CV_INPUT));
        addInput(createInputCentered<PJ301MPort>(
            Vec(xCenter + 25, 200), module, LadderLPF::RESONANCE_CV_INPUT));

        // Audio I/O
        addInput(createInputCentered<PJ301MPort>(
            Vec(xCenter - 25, 280), module, LadderLPF::AUDIO_INPUT));
        addOutput(createOutputCentered<PJ301MPort>(
            Vec(xCenter + 25, 280), module, LadderLPF::AUDIO_OUTPUT));
    }
};

} // namespace WiggleRoom

Model* modelLadderLPF = createModel<WiggleRoom::LadderLPF, WiggleRoom::LadderLPFWidget>("LadderLPF");
