/******************************************************************************
 * SPECTRAL RESONATOR
 * 6-band resonant filter bank for spectral chord processing
 * Inspired by 4ms SMR and Mutable Instruments Rings
 * Built with Faust DSP
 ******************************************************************************/

#include "rack.hpp"
#include "FaustModule.hpp"
#define FAUST_MODULE_NAME SpectralResonator
#include "spectral_resonator.hpp"  // Generated by Faust

using namespace rack;

extern Plugin* pluginInstance;

namespace WiggleRoom {

/**
 * SpectralResonator - 6-Band Chord Resonator
 *
 * A bank of 6 tuned resonant filters that transform noise, drums,
 * or simple waves into lush, melodic chords.
 *
 * Features:
 *   - 6 parallel resonant bandpass filters
 *   - Spread control morphs between unison, fifths, octaves, and complex chords
 *   - Stereo output: odd bands (1,3,5) to left, even bands (2,4,6) to right
 *   - V/Oct pitch tracking
 *   - CV control over spread for "breathing" chord effects
 */
struct SpectralResonator : FaustModule<VCVRackDSP> {
    enum ParamId {
        FREQ_PARAM,      // Center frequency (volts)
        SPREAD_PARAM,    // Chord spread (1.0 = unison, 2.0 = octaves)
        Q_PARAM,         // Resonance
        DAMP_PARAM,      // Damping (lowpass cutoff)
        PARAMS_LEN
    };
    enum InputId {
        AUDIO_INPUT,     // Mono audio input
        VOCT_INPUT,      // 1V/Oct pitch CV
        SPREAD_CV_INPUT, // Spread modulation
        INPUTS_LEN
    };
    enum OutputId {
        LEFT_OUTPUT,
        RIGHT_OUTPUT,
        OUTPUTS_LEN
    };
    enum LightId {
        LIGHTS_LEN
    };

    SpectralResonator() {
        config(PARAMS_LEN, INPUTS_LEN, OUTPUTS_LEN, LIGHTS_LEN);

        // Configure parameters
        // Freq knob represents V/Oct (0V = 110Hz A2, 4V = 1760Hz A5)
        configParam(FREQ_PARAM, 0.f, 10.f, 4.f, "Center Frequency", " V");
        configParam(SPREAD_PARAM, 1.0f, 3.0f, 1.5f, "Chord Spread");
        configParam(Q_PARAM, 1.f, 100.f, 50.f, "Resonance (Q)");
        configParam(DAMP_PARAM, 1000.f, 20000.f, 10000.f, "Damping", " Hz");

        // Configure inputs
        configInput(AUDIO_INPUT, "Audio");
        configInput(VOCT_INPUT, "V/Oct");
        configInput(SPREAD_CV_INPUT, "Spread CV");

        // Configure outputs
        configOutput(LEFT_OUTPUT, "Left");
        configOutput(RIGHT_OUTPUT, "Right");

        // Faust params (alphabetical): damp=0, q=1, spread=2, volts=3
        mapParam(DAMP_PARAM, 0);
        mapParam(Q_PARAM, 1);
        mapParam(SPREAD_PARAM, 2);
        mapParam(FREQ_PARAM, 3);
    }

    void process(const ProcessArgs& args) override {
        // Initialize DSP on first run
        if (!initialized) {
            faustDsp.init(static_cast<int>(args.sampleRate));
            initialized = true;
        }

        // Calculate pitch (knob + V/Oct input)
        float volts = params[FREQ_PARAM].getValue();
        if (inputs[VOCT_INPUT].isConnected()) {
            volts += inputs[VOCT_INPUT].getVoltage();
        }
        volts = clamp(volts, 0.f, 10.f);

        // Calculate spread (knob + CV)
        float spread = params[SPREAD_PARAM].getValue();
        if (inputs[SPREAD_CV_INPUT].isConnected()) {
            spread += inputs[SPREAD_CV_INPUT].getVoltage() * 0.2f;  // +/-5V = +/-1.0
        }
        spread = clamp(spread, 1.001f, 3.0f);  // Prevent 0 or negative spread

        // Update Faust parameters (alphabetical order)
        faustDsp.setParamValue(0, params[DAMP_PARAM].getValue());  // damp
        faustDsp.setParamValue(1, params[Q_PARAM].getValue());      // q
        faustDsp.setParamValue(2, spread);                          // spread (with CV)
        faustDsp.setParamValue(3, volts);                           // volts (with V/Oct)

        // Get mono input (normalize to Faust range)
        float input = inputs[AUDIO_INPUT].getVoltage() * 0.2f;  // 5V -> 1.0

        float* inputPtrs[1] = { &input };
        float outputL = 0.0f, outputR = 0.0f;
        float* outputPtrs[2] = { &outputL, &outputR };

        // Process audio
        faustDsp.compute(1, inputPtrs, outputPtrs);

        // Output (back to VCV voltage range)
        outputs[LEFT_OUTPUT].setVoltage(outputL * 5.0f);
        outputs[RIGHT_OUTPUT].setVoltage(outputR * 5.0f);
    }
};

struct SpectralResonatorWidget : ModuleWidget {
    SpectralResonatorWidget(SpectralResonator* module) {
        setModule(module);
        setPanel(createPanel(asset::plugin(pluginInstance, "res/SpectralResonator.svg")));

        // Screws
        addChild(createWidget<ScrewSilver>(Vec(RACK_GRID_WIDTH, 0)));
        addChild(createWidget<ScrewSilver>(Vec(box.size.x - 2 * RACK_GRID_WIDTH, 0)));
        addChild(createWidget<ScrewSilver>(Vec(RACK_GRID_WIDTH, RACK_GRID_HEIGHT - RACK_GRID_WIDTH)));
        addChild(createWidget<ScrewSilver>(Vec(box.size.x - 2 * RACK_GRID_WIDTH, RACK_GRID_HEIGHT - RACK_GRID_WIDTH)));

        float xCenter = box.size.x / 2.0f;

        // Big Frequency knob at top
        addParam(createParamCentered<RoundBigBlackKnob>(
            Vec(xCenter, 55), module, SpectralResonator::FREQ_PARAM));

        // Spread knob
        addParam(createParamCentered<RoundBlackKnob>(
            Vec(xCenter, 110), module, SpectralResonator::SPREAD_PARAM));

        // Q and Damp knobs side by side
        addParam(createParamCentered<RoundBlackKnob>(
            Vec(xCenter - 20, 160), module, SpectralResonator::Q_PARAM));
        addParam(createParamCentered<RoundBlackKnob>(
            Vec(xCenter + 20, 160), module, SpectralResonator::DAMP_PARAM));

        // CV Inputs
        addInput(createInputCentered<PJ301MPort>(
            Vec(xCenter - 20, 210), module, SpectralResonator::VOCT_INPUT));
        addInput(createInputCentered<PJ301MPort>(
            Vec(xCenter + 20, 210), module, SpectralResonator::SPREAD_CV_INPUT));

        // Audio Input (mono)
        addInput(createInputCentered<PJ301MPort>(
            Vec(xCenter, 260), module, SpectralResonator::AUDIO_INPUT));

        // Stereo Outputs
        addOutput(createOutputCentered<PJ301MPort>(
            Vec(xCenter - 20, 310), module, SpectralResonator::LEFT_OUTPUT));
        addOutput(createOutputCentered<PJ301MPort>(
            Vec(xCenter + 20, 310), module, SpectralResonator::RIGHT_OUTPUT));
    }
};

} // namespace WiggleRoom

Model* modelSpectralResonator = createModel<WiggleRoom::SpectralResonator, WiggleRoom::SpectralResonatorWidget>("SpectralResonator");
