/******************************************************************************
 * LINKAGE - Chaotic Percussion Generator
 * Physical model: chain of 3 masses connected by loose non-linear springs
 * Strike the top mass, listen to the bottom mass rattle.
 * Built with Faust DSP
 ******************************************************************************/

#include "rack.hpp"
#include "FaustModule.hpp"
#define FAUST_MODULE_NAME Linkage
#include "linkage.hpp"  // Generated by Faust

using namespace rack;

extern Plugin* pluginInstance;

namespace WiggleRoom {

/**
 * Linkage - Chaotic Percussion Generator
 *
 * Simulates a chain of 3 masses connected by loose, non-linear springs.
 * When you strike the top mass, energy ripples down creating rattling,
 * metallic, and delayed rhythms.
 *
 * Parameters:
 *   - Tension: Spring stiffness (high = metallic, low = rattle)
 *   - Damping: Energy loss (high = thud, low = long rattle)
 *   - Slack: Non-linearity threshold (creates chaotic clinking)
 *
 * Inputs:
 *   - Gate: Strike trigger
 *   - Tension CV: Modulate spring stiffness
 *   - Slack CV: Modulate chaos amount
 */
struct Linkage : FaustModule<VCVRackDSP> {
    enum ParamId {
        TENSION_PARAM,
        DAMPING_PARAM,
        SLACK_PARAM,
        PARAMS_LEN
    };
    enum InputId {
        GATE_INPUT,
        TENSION_CV_INPUT,
        SLACK_CV_INPUT,
        INPUTS_LEN
    };
    enum OutputId {
        AUDIO_OUTPUT,
        OUTPUTS_LEN
    };
    enum LightId {
        LIGHTS_LEN
    };

    dsp::SchmittTrigger gateTrigger;

    Linkage() {
        config(PARAMS_LEN, INPUTS_LEN, OUTPUTS_LEN, LIGHTS_LEN);

        // Configure parameters
        configParam(TENSION_PARAM, 10.f, 200.f, 50.f, "Tension / Pitch");
        configParam(DAMPING_PARAM, 0.001f, 0.5f, 0.1f, "Damping");
        configParam(SLACK_PARAM, 0.f, 0.5f, 0.0f, "Slack / Chaos");

        // Configure inputs
        configInput(GATE_INPUT, "Gate");
        configInput(TENSION_CV_INPUT, "Tension CV");
        configInput(SLACK_CV_INPUT, "Slack CV");

        // Configure outputs
        configOutput(AUDIO_OUTPUT, "Audio");

        // Map VCV parameters to Faust DSP parameters
        // Faust params (alphabetical): damping=0, gate=1, slack=2, tension=3
        mapParam(DAMPING_PARAM, 0);
        mapParam(SLACK_PARAM, 2);
        mapParam(TENSION_PARAM, 3);

        // Map CV inputs with linear modulation
        // Tension: ±20 per volt for pitch-like control
        // Slack: ±0.1 per volt for subtle chaos modulation
        mapCVInput(TENSION_CV_INPUT, 3, false, 20.f);
        mapCVInput(SLACK_CV_INPUT, 2, false, 0.1f);
    }

    void process(const ProcessArgs& args) override {
        // Initialize DSP on first run
        if (!initialized) {
            faustDsp.init(static_cast<int>(args.sampleRate));
            initialized = true;
        }

        // Update all mapped parameters (knobs + CV modulation)
        updateFaustParams();

        // Handle gate trigger - convert to 0/1 for Faust button
        float gateValue = 0.f;
        if (gateTrigger.process(inputs[GATE_INPUT].getVoltage(), 0.1f, 1.f)) {
            gateValue = 1.f;
        }
        // Faust param: gate=1
        faustDsp.setParamValue(1, gateValue);

        // Process audio (no input, mono output)
        float* nullInputs[1] = { nullptr };
        float output = 0.f;
        float* outputPtrs[1] = { &output };

        faustDsp.compute(1, nullInputs, outputPtrs);

        // Hard clip for safety (physics can be bursty) and scale to VCV levels
        output = clamp(output, -2.f, 2.f);
        outputs[AUDIO_OUTPUT].setVoltage(output * 5.f);
    }
};

struct LinkageWidget : ModuleWidget {
    LinkageWidget(Linkage* module) {
        setModule(module);
        setPanel(createPanel(asset::plugin(pluginInstance, "res/Linkage.svg")));

        // Screws
        addChild(createWidget<ScrewSilver>(Vec(RACK_GRID_WIDTH, 0)));
        addChild(createWidget<ScrewSilver>(Vec(box.size.x - 2 * RACK_GRID_WIDTH, 0)));
        addChild(createWidget<ScrewSilver>(Vec(RACK_GRID_WIDTH, RACK_GRID_HEIGHT - RACK_GRID_WIDTH)));
        addChild(createWidget<ScrewSilver>(Vec(box.size.x - 2 * RACK_GRID_WIDTH, RACK_GRID_HEIGHT - RACK_GRID_WIDTH)));

        float xCenter = box.size.x / 2.f;
        float xLeft = box.size.x * 0.25f;
        float xRight = box.size.x * 0.75f;

        // Main Tension knob (large) - controls pitch/metallic character
        addParam(createParamCentered<RoundBigBlackKnob>(
            Vec(xCenter, 60), module, Linkage::TENSION_PARAM));

        // Slack knob - controls chaos/rattle
        addParam(createParamCentered<RoundBlackKnob>(
            Vec(xCenter, 115), module, Linkage::SLACK_PARAM));

        // Damping knob - controls decay
        addParam(createParamCentered<RoundBlackKnob>(
            Vec(xCenter, 165), module, Linkage::DAMPING_PARAM));

        // CV inputs
        addInput(createInputCentered<PJ301MPort>(
            Vec(xLeft, 220), module, Linkage::TENSION_CV_INPUT));
        addInput(createInputCentered<PJ301MPort>(
            Vec(xRight, 220), module, Linkage::SLACK_CV_INPUT));

        // Gate input
        addInput(createInputCentered<PJ301MPort>(
            Vec(xCenter, 270), module, Linkage::GATE_INPUT));

        // Audio output
        addOutput(createOutputCentered<PJ301MPort>(
            Vec(xCenter, 320), module, Linkage::AUDIO_OUTPUT));
    }
};

} // namespace WiggleRoom

Model* modelLinkage = createModel<WiggleRoom::Linkage, WiggleRoom::LinkageWidget>("Linkage");
