/******************************************************************************
 * MODAL BELL
 * Physical model of a struck bar - Vibraphone, Marimba, Bell sounds
 * Built with Faust DSP
 ******************************************************************************/

#include "rack.hpp"
#include "FaustModule.hpp"
#define FAUST_MODULE_NAME ModalBell
#include "modal_bell.hpp"  // Generated by Faust

using namespace rack;

extern Plugin* pluginInstance;

namespace WiggleRoom {

/**
 * ModalBell - Physical Model of a Struck Bar
 *
 * A physically modeled instrument that sounds like a Vibraphone,
 * Marimba, or glassy bell depending on the knob settings.
 *
 * Inputs:
 *   - V/Oct: Pitch control (0V = C4)
 *   - Gate: Trigger input (strikes when > 1V)
 *
 * Parameters:
 *   - Hardness: Mallet softness (0 = soft, 1 = hard)
 *   - Position: Strike position on bar (0 = edge, 1 = center)
 *   - Preset: Instrument type (Marimba, Vibraphone, etc.)
 */
struct ModalBell : FaustModule<VCVRackDSP> {
    enum ParamId {
        BRIGHTNESS_PARAM,
        DECAY_PARAM,
        MATERIAL_PARAM,
        PARAMS_LEN
    };
    enum InputId {
        VOCT_INPUT,
        GATE_INPUT,
        INPUTS_LEN
    };
    enum OutputId {
        LEFT_OUTPUT,
        RIGHT_OUTPUT,
        OUTPUTS_LEN
    };
    enum LightId {
        LIGHTS_LEN
    };

    ModalBell() {
        config(PARAMS_LEN, INPUTS_LEN, OUTPUTS_LEN, LIGHTS_LEN);

        // Configure parameters
        configParam(BRIGHTNESS_PARAM, 0.0f, 1.0f, 0.5f, "Brightness", "%", 0.f, 100.f);
        configParam(DECAY_PARAM, 0.1f, 5.0f, 0.5f, "Decay", " s");
        configParam(MATERIAL_PARAM, 0.0f, 1.0f, 0.5f, "Material", "", 0.f, 1.f);

        // Configure inputs
        configInput(VOCT_INPUT, "V/Oct");
        configInput(GATE_INPUT, "Gate");

        // Configure outputs
        configOutput(LEFT_OUTPUT, "Left");
        configOutput(RIGHT_OUTPUT, "Right");

        // Map VCV parameters to Faust DSP parameters
        // Faust params order: volts, gate, brightness, decay, material
        mapParam(BRIGHTNESS_PARAM, 0);  // brightness
        mapParam(DECAY_PARAM, 1);       // decay
        mapParam(MATERIAL_PARAM, 3);    // material
    }

    void process(const ProcessArgs& args) override {
        // Initialize DSP on first run
        if (!initialized) {
            faustDsp.init(static_cast<int>(args.sampleRate));
            initialized = true;
        }

        // Get V/Oct and Gate inputs and send directly to Faust
        float voct = inputs[VOCT_INPUT].getVoltage();
        float gate = inputs[GATE_INPUT].getVoltage();

        // Set Faust parameters for inputs (volts=4, gate=2 based on alphabetical order)
        faustDsp.setParamValue(4, voct);   // volts
        faustDsp.setParamValue(2, gate);   // gate

        // Set knob values
        faustDsp.setParamValue(0, params[BRIGHTNESS_PARAM].getValue());
        faustDsp.setParamValue(1, params[DECAY_PARAM].getValue());
        faustDsp.setParamValue(3, params[MATERIAL_PARAM].getValue());

        // Process audio (no input, stereo output)
        float* nullInputs[1] = { nullptr };
        float outputL = 0.0f, outputR = 0.0f;
        float* outputPtrs[2] = { &outputL, &outputR };

        faustDsp.compute(1, nullInputs, outputPtrs);

        // Output at 5V peak
        outputs[LEFT_OUTPUT].setVoltage(outputL * 5.0f);
        outputs[RIGHT_OUTPUT].setVoltage(outputR * 5.0f);
    }
};

struct ModalBellWidget : ModuleWidget {
    ModalBellWidget(ModalBell* module) {
        setModule(module);
        setPanel(createPanel(asset::plugin(pluginInstance, "res/ModalBell.svg")));

        // Screws
        addChild(createWidget<ScrewSilver>(Vec(RACK_GRID_WIDTH, 0)));
        addChild(createWidget<ScrewSilver>(Vec(box.size.x - 2 * RACK_GRID_WIDTH, 0)));
        addChild(createWidget<ScrewSilver>(Vec(RACK_GRID_WIDTH, RACK_GRID_HEIGHT - RACK_GRID_WIDTH)));
        addChild(createWidget<ScrewSilver>(Vec(box.size.x - 2 * RACK_GRID_WIDTH, RACK_GRID_HEIGHT - RACK_GRID_WIDTH)));

        float xCenter = box.size.x / 2.0f;

        // Knobs
        addParam(createParamCentered<RoundBigBlackKnob>(
            Vec(xCenter, 70), module, ModalBell::DECAY_PARAM));
        addParam(createParamCentered<RoundBlackKnob>(
            Vec(xCenter - 20, 130), module, ModalBell::BRIGHTNESS_PARAM));
        addParam(createParamCentered<RoundBlackKnob>(
            Vec(xCenter + 20, 130), module, ModalBell::MATERIAL_PARAM));

        // Inputs
        addInput(createInputCentered<PJ301MPort>(
            Vec(xCenter - 20, 200), module, ModalBell::VOCT_INPUT));
        addInput(createInputCentered<PJ301MPort>(
            Vec(xCenter + 20, 200), module, ModalBell::GATE_INPUT));

        // Outputs
        addOutput(createOutputCentered<PJ301MPort>(
            Vec(xCenter - 20, 280), module, ModalBell::LEFT_OUTPUT));
        addOutput(createOutputCentered<PJ301MPort>(
            Vec(xCenter + 20, 280), module, ModalBell::RIGHT_OUTPUT));
    }
};

} // namespace WiggleRoom

Model* modelModalBell = createModel<WiggleRoom::ModalBell, WiggleRoom::ModalBellWidget>("ModalBell");
